<?php

use common\models\CountryPhoneCode;
use yii\db\Migration;

/**
 * Class m160719_080240_country_phone_code_data
 */
class m160719_080240_country_phone_code_data extends Migration
{
    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->insert(CountryPhoneCode::tableName(), ['id' => 1, 'country_code' => 'AF', 'name' => 'Afghanistan (‫افغانستان‬‎)', 'number' => '93']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 2, 'country_code' => 'AL', 'name' => 'Albania (Shqipëri)', 'number' => '355']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 3, 'country_code' => 'DZ', 'name' => 'Algeria (‫الجزائر‬‎)', 'number' => '213']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 4, 'country_code' => 'AS', 'name' => 'American Samoa', 'number' => '1684']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 5, 'country_code' => 'AD', 'name' => 'Andorra', 'number' => '376']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 6, 'country_code' => 'AO', 'name' => 'Angola', 'number' => '244']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 7, 'country_code' => 'AI', 'name' => 'Anguilla', 'number' => '1264']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 8, 'country_code' => 'AG', 'name' => 'Antigua and Barbuda', 'number' => '1268']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 9, 'country_code' => 'AR', 'name' => 'Argentina', 'number' => '54']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 10, 'country_code' => 'AM', 'name' => 'Armenia (Հայաստան)', 'number' => '374']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 11, 'country_code' => 'AW', 'name' => 'Aruba', 'number' => '297']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 12, 'country_code' => 'AU', 'name' => 'Australia', 'number' => '61']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 13, 'country_code' => 'AT', 'name' => 'Austria (Österreich)', 'number' => '43']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 14, 'country_code' => 'AZ', 'name' => 'Azerbaijan (Azərbaycan)', 'number' => '994']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 15, 'country_code' => 'BS', 'name' => 'Bahamas', 'number' => '1242']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 16, 'country_code' => 'BH', 'name' => 'Bahrain (‫البحرين‬‎)', 'number' => '973']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 17, 'country_code' => 'BD', 'name' => 'Bangladesh (বাংলাদেশ)', 'number' => '880']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 18, 'country_code' => 'BB', 'name' => 'Barbados', 'number' => '1246']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 19, 'country_code' => 'BY', 'name' => 'Belarus (Беларусь)', 'number' => '375']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 20, 'country_code' => 'BE', 'name' => 'Belgium (België)', 'number' => '32']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 21, 'country_code' => 'BZ', 'name' => 'Belize', 'number' => '501']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 22, 'country_code' => 'BJ', 'name' => 'Benin (Bénin)', 'number' => '229']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 23, 'country_code' => 'BM', 'name' => 'Bermuda', 'number' => '1441']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 24, 'country_code' => 'BT', 'name' => 'Bhutan (འབྲུག)', 'number' => '975']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 25, 'country_code' => 'BO', 'name' => 'Bolivia', 'number' => '591']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 26, 'country_code' => 'BA', 'name' => 'Bosnia and Herzegovina (Босна и Херцеговина)', 'number' => '387']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 27, 'country_code' => 'BW', 'name' => 'Botswana', 'number' => '267']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 28, 'country_code' => 'BR', 'name' => 'Brazil (Brasil)', 'number' => '55']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 29, 'country_code' => 'IO', 'name' => 'British Indian Ocean Territory', 'number' => '246']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 30, 'country_code' => 'VG', 'name' => 'British Virgin Islands', 'number' => '1284']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 31, 'country_code' => 'BN', 'name' => 'Brunei', 'number' => '673']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 32, 'country_code' => 'BG', 'name' => 'Bulgaria (България)', 'number' => '359']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 33, 'country_code' => 'BF', 'name' => 'Burkina Faso', 'number' => '226']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 34, 'country_code' => 'BI', 'name' => 'Burundi (Uburundi)', 'number' => '257']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 35, 'country_code' => 'KH', 'name' => 'Cambodia (កម្ពុជា)', 'number' => '855']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 36, 'country_code' => 'CM', 'name' => 'Cameroon (Cameroun)', 'number' => '237']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 37, 'country_code' => 'CA', 'name' => 'Canada', 'number' => '1']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 38, 'country_code' => 'CV', 'name' => 'Cape Verde (Kabu Verdi)', 'number' => '238']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 39, 'country_code' => 'BQ', 'name' => 'Caribbean Netherlands', 'number' => '5997']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 40, 'country_code' => 'KY', 'name' => 'Cayman Islands', 'number' => '1345']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 41, 'country_code' => 'CF', 'name' => 'Central African Republic (République centrafricaine)', 'number' => '236']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 42, 'country_code' => 'TD', 'name' => 'Chad (Tchad)', 'number' => '235']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 43, 'country_code' => 'CL', 'name' => 'Chile', 'number' => '56']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 44, 'country_code' => 'CN', 'name' => 'China (中国)', 'number' => '86']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 45, 'country_code' => 'CX', 'name' => 'Christmas Island', 'number' => '61']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 46, 'country_code' => 'CC', 'name' => 'Cocos (Keeling) Islands (Kepulauan Cocos (Keeling))', 'number' => '61']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 47, 'country_code' => 'CO', 'name' => 'Colombia', 'number' => '57']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 48, 'country_code' => 'KM', 'name' => 'Comoros (‫جزر القمر‬‎)', 'number' => '269']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 49, 'country_code' => 'CD', 'name' => 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', 'number' => '243']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 50, 'country_code' => 'CG', 'name' => 'Congo (Republic) (Congo-Brazzaville)', 'number' => '242']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 51, 'country_code' => 'CK', 'name' => 'Cook Islands', 'number' => '682']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 52, 'country_code' => 'CR', 'name' => 'Costa Rica', 'number' => '506']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 53, 'country_code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'number' => '385']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 54, 'country_code' => 'CU', 'name' => 'Cuba', 'number' => '53']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 55, 'country_code' => 'CW', 'name' => 'Curaçao', 'number' => '5999']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 56, 'country_code' => 'CY', 'name' => 'Cyprus (Κύπρος)', 'number' => '357']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 57, 'country_code' => 'CZ', 'name' => 'Czech Republic (Česká republika)', 'number' => '420']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 58, 'country_code' => 'CI', 'name' => 'Côte d’Ivoire', 'number' => '225']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 59, 'country_code' => 'DK', 'name' => 'Denmark (Danmark)', 'number' => '45']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 60, 'country_code' => 'DJ', 'name' => 'Djibouti', 'number' => '253']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 61, 'country_code' => 'DM', 'name' => 'Dominica', 'number' => '1767']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 62, 'country_code' => 'DO', 'name' => 'Dominican Republic (República Dominicana)', 'number' => '1809']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 63, 'country_code' => 'EC', 'name' => 'Ecuador', 'number' => '593']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 64, 'country_code' => 'EG', 'name' => 'Egypt (‫مصر‬‎)', 'number' => '20']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 65, 'country_code' => 'SV', 'name' => 'El Salvador', 'number' => '503']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 66, 'country_code' => 'GQ', 'name' => 'Equatorial Guinea (Guinea Ecuatorial)', 'number' => '240']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 67, 'country_code' => 'ER', 'name' => 'Eritrea', 'number' => '291']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 68, 'country_code' => 'EE', 'name' => 'Estonia (Eesti)', 'number' => '372']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 69, 'country_code' => 'ET', 'name' => 'Ethiopia', 'number' => '251']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 70, 'country_code' => 'FK', 'name' => 'Falkland Islands (Islas Malvinas)', 'number' => '500']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 71, 'country_code' => 'FO', 'name' => 'Faroe Islands (Føroyar)', 'number' => '298']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 72, 'country_code' => 'FJ', 'name' => 'Fiji', 'number' => '679']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 73, 'country_code' => 'FI', 'name' => 'Finland (Suomi)', 'number' => '358']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 74, 'country_code' => 'FR', 'name' => 'France', 'number' => '33']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 75, 'country_code' => 'GF', 'name' => 'French Guiana (Guyane française)', 'number' => '594']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 76, 'country_code' => 'PF', 'name' => 'French Polynesia (Polynésie française)', 'number' => '689']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 77, 'country_code' => 'GA', 'name' => 'Gabon', 'number' => '241']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 78, 'country_code' => 'GM', 'name' => 'Gambia', 'number' => '220']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 79, 'country_code' => 'GE', 'name' => 'Georgia (საქართველო)', 'number' => '995']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 80, 'country_code' => 'DE', 'name' => 'Germany (Deutschland)', 'number' => '49']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 81, 'country_code' => 'GH', 'name' => 'Ghana (Gaana)', 'number' => '233']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 82, 'country_code' => 'GI', 'name' => 'Gibraltar', 'number' => '350']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 83, 'country_code' => 'GR', 'name' => 'Greece (Ελλάδα)', 'number' => '30']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 84, 'country_code' => 'GL', 'name' => 'Greenland (Kalaallit Nunaat)', 'number' => '299']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 85, 'country_code' => 'GD', 'name' => 'Grenada', 'number' => '1473']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 86, 'country_code' => 'GP', 'name' => 'Guadeloupe', 'number' => '590']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 87, 'country_code' => 'GU', 'name' => 'Guam', 'number' => '1671']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 88, 'country_code' => 'GT', 'name' => 'Guatemala', 'number' => '502']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 89, 'country_code' => 'GG', 'name' => 'Guernsey', 'number' => '44']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 90, 'country_code' => 'GN', 'name' => 'Guinea (Guinée)', 'number' => '224']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 91, 'country_code' => 'GW', 'name' => 'Guinea-Bissau (Guiné Bissau)', 'number' => '245']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 92, 'country_code' => 'GY', 'name' => 'Guyana', 'number' => '592']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 93, 'country_code' => 'HT', 'name' => 'Haiti', 'number' => '509']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 94, 'country_code' => 'HN', 'name' => 'Honduras', 'number' => '504']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 95, 'country_code' => 'HK', 'name' => 'Hong Kong (香港)', 'number' => '852']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 96, 'country_code' => 'HU', 'name' => 'Hungary (Magyarország)', 'number' => '36']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 97, 'country_code' => 'IS', 'name' => 'Iceland (Ísland)', 'number' => '354']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 98, 'country_code' => 'IN', 'name' => 'India (भारत)', 'number' => '91']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 99, 'country_code' => 'ID', 'name' => 'Indonesia', 'number' => '62']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 100, 'country_code' => 'IR', 'name' => 'Iran (‫ایران‬‎)', 'number' => '98']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 101, 'country_code' => 'IQ', 'name' => 'Iraq (‫العراق‬‎)', 'number' => '964']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 102, 'country_code' => 'IE', 'name' => 'Ireland', 'number' => '353']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 103, 'country_code' => 'IM', 'name' => 'Isle of Man', 'number' => '44']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 104, 'country_code' => 'IL', 'name' => 'Israel (‫ישראל‬‎)', 'number' => '972']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 105, 'country_code' => 'IT', 'name' => 'Italy (Italia)', 'number' => '39']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 106, 'country_code' => 'JM', 'name' => 'Jamaica', 'number' => '1876']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 107, 'country_code' => 'JP', 'name' => 'Japan (日本)', 'number' => '81']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 108, 'country_code' => 'JE', 'name' => 'Jersey', 'number' => '44']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 109, 'country_code' => 'JO', 'name' => 'Jordan (‫الأردن‬‎)', 'number' => '962']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 110, 'country_code' => 'KZ', 'name' => 'Kazakhstan (Казахстан)', 'number' => '7']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 111, 'country_code' => 'KE', 'name' => 'Kenya', 'number' => '254']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 112, 'country_code' => 'KI', 'name' => 'Kiribati', 'number' => '686']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 113, 'country_code' => 'XK', 'name' => 'Kosovo (Kosovë)', 'number' => '377']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 114, 'country_code' => 'KW', 'name' => 'Kuwait (‫الكويت‬‎)', 'number' => '965']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 115, 'country_code' => 'KG', 'name' => 'Kyrgyzstan (Кыргызстан)', 'number' => '996']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 116, 'country_code' => 'LA', 'name' => 'Laos (ລາວ)', 'number' => '856']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 117, 'country_code' => 'LV', 'name' => 'Latvia (Latvija)', 'number' => '371']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 118, 'country_code' => 'LB', 'name' => 'Lebanon (‫لبنان‬‎)', 'number' => '961']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 119, 'country_code' => 'LS', 'name' => 'Lesotho', 'number' => '266']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 120, 'country_code' => 'LR', 'name' => 'Liberia', 'number' => '231']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 121, 'country_code' => 'LY', 'name' => 'Libya (‫ليبيا‬‎)', 'number' => '218']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 122, 'country_code' => 'LI', 'name' => 'Liechtenstein', 'number' => '423']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 123, 'country_code' => 'LT', 'name' => 'Lithuania (Lietuva)', 'number' => '370']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 124, 'country_code' => 'LU', 'name' => 'Luxembourg', 'number' => '352']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 125, 'country_code' => 'MO', 'name' => 'Macau (澳門)', 'number' => '853']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 126, 'country_code' => 'MK', 'name' => 'Macedonia (FYROM) (Македонија)', 'number' => '389']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 127, 'country_code' => 'MG', 'name' => 'Madagascar (Madagasikara)', 'number' => '261']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 128, 'country_code' => 'MW', 'name' => 'Malawi', 'number' => '265']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 129, 'country_code' => 'MY', 'name' => 'Malaysia', 'number' => '60']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 130, 'country_code' => 'MV', 'name' => 'Maldives', 'number' => '960']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 131, 'country_code' => 'ML', 'name' => 'Mali', 'number' => '223']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 132, 'country_code' => 'MT', 'name' => 'Malta', 'number' => '356']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 133, 'country_code' => 'MH', 'name' => 'Marshall Islands', 'number' => '692']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 134, 'country_code' => 'MQ', 'name' => 'Martinique', 'number' => '596']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 135, 'country_code' => 'MR', 'name' => 'Mauritania (‫موريتانيا‬‎)', 'number' => '222']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 136, 'country_code' => 'MU', 'name' => 'Mauritius (Moris)', 'number' => '230']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 137, 'country_code' => 'YT', 'name' => 'Mayotte', 'number' => '262']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 138, 'country_code' => 'MX', 'name' => 'Mexico (México)', 'number' => '52']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 139, 'country_code' => 'FM', 'name' => 'Micronesia', 'number' => '691']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 140, 'country_code' => 'MD', 'name' => 'Moldova (Republica Moldova)', 'number' => '373']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 141, 'country_code' => 'MC', 'name' => 'Monaco', 'number' => '377']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 142, 'country_code' => 'MN', 'name' => 'Mongolia (Монгол)', 'number' => '976']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 143, 'country_code' => 'ME', 'name' => 'Montenegro (Crna Gora)', 'number' => '382']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 144, 'country_code' => 'MS', 'name' => 'Montserrat', 'number' => '1664']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 145, 'country_code' => 'MA', 'name' => 'Morocco (‫المغرب‬‎)', 'number' => '212']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 146, 'country_code' => 'MZ', 'name' => 'Mozambique (Moçambique)', 'number' => '258']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 147, 'country_code' => 'MM', 'name' => 'Myanmar (Burma) (မြန်မာ)', 'number' => '95']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 148, 'country_code' => 'NA', 'name' => 'Namibia (Namibië)', 'number' => '264']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 149, 'country_code' => 'NR', 'name' => 'Nauru', 'number' => '674']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 150, 'country_code' => 'NP', 'name' => 'Nepal (नेपाल)', 'number' => '977']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 151, 'country_code' => 'NL', 'name' => 'Netherlands (Nederland)', 'number' => '31']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 152, 'country_code' => 'NC', 'name' => 'New Caledonia (Nouvelle-Calédonie)', 'number' => '687']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 153, 'country_code' => 'NZ', 'name' => 'New Zealand', 'number' => '64']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 154, 'country_code' => 'NI', 'name' => 'Nicaragua', 'number' => '505']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 155, 'country_code' => 'NE', 'name' => 'Niger (Nijar)', 'number' => '227']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 156, 'country_code' => 'NG', 'name' => 'Nigeria', 'number' => '234']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 157, 'country_code' => 'NU', 'name' => 'Niue', 'number' => '683']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 158, 'country_code' => 'NF', 'name' => 'Norfolk Island', 'number' => '672']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 159, 'country_code' => 'KP', 'name' => 'North Korea (조선 민주주의 인민 공화국)', 'number' => '850']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 160, 'country_code' => 'MP', 'name' => 'Northern Mariana Islands', 'number' => '1670']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 161, 'country_code' => 'NO', 'name' => 'Norway (Norge)', 'number' => '47']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 162, 'country_code' => 'OM', 'name' => 'Oman (‫عُمان‬‎)', 'number' => '968']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 163, 'country_code' => 'PK', 'name' => 'Pakistan (‫پاکستان‬‎)', 'number' => '92']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 164, 'country_code' => 'PW', 'name' => 'Palau', 'number' => '680']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 165, 'country_code' => 'PS', 'name' => 'Palestine (‫فلسطين‬‎)', 'number' => '970']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 166, 'country_code' => 'PA', 'name' => 'Panama (Panamá)', 'number' => '507']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 167, 'country_code' => 'PG', 'name' => 'Papua New Guinea', 'number' => '675']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 168, 'country_code' => 'PY', 'name' => 'Paraguay', 'number' => '595']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 169, 'country_code' => 'PE', 'name' => 'Peru (Perú)', 'number' => '51']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 170, 'country_code' => 'PH', 'name' => 'Philippines', 'number' => '63']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 171, 'country_code' => 'PN', 'name' => 'Pitcairn Islands', 'number' => '64']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 172, 'country_code' => 'PL', 'name' => 'Poland (Polska)', 'number' => '48']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 173, 'country_code' => 'PT', 'name' => 'Portugal', 'number' => '351']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 174, 'country_code' => 'PR', 'name' => 'Puerto Rico', 'number' => '1787']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 175, 'country_code' => 'QA', 'name' => 'Qatar (‫قطر‬‎)', 'number' => '974']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 176, 'country_code' => 'RO', 'name' => 'Romania (România)', 'number' => '40']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 177, 'country_code' => 'RU', 'name' => 'Russia (Россия)', 'number' => '7']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 178, 'country_code' => 'RW', 'name' => 'Rwanda', 'number' => '250']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 179, 'country_code' => 'RE', 'name' => 'Réunion (La Réunion)', 'number' => '262']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 180, 'country_code' => 'BL', 'name' => 'Saint Barthélemy (Saint-Barthélemy)', 'number' => '590']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 181, 'country_code' => 'SH', 'name' => 'Saint Helena', 'number' => '290']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 182, 'country_code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'number' => '1869']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 183, 'country_code' => 'LC', 'name' => 'Saint Lucia', 'number' => '1758']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 184, 'country_code' => 'MF', 'name' => 'Saint Martin (Saint-Martin (partie française))', 'number' => '590']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 185, 'country_code' => 'PM', 'name' => 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)', 'number' => '508']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 186, 'country_code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'number' => '1784']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 187, 'country_code' => 'WS', 'name' => 'Samoa', 'number' => '685']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 188, 'country_code' => 'SM', 'name' => 'San Marino', 'number' => '378']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 189, 'country_code' => 'SA', 'name' => 'Saudi Arabia (‫المملكة العربية السعودية‬‎)', 'number' => '966']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 190, 'country_code' => 'SN', 'name' => 'Senegal (Sénégal)', 'number' => '221']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 191, 'country_code' => 'RS', 'name' => 'Serbia (Србија)', 'number' => '381']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 192, 'country_code' => 'SC', 'name' => 'Seychelles', 'number' => '248']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 193, 'country_code' => 'SL', 'name' => 'Sierra Leone', 'number' => '232']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 194, 'country_code' => 'SG', 'name' => 'Singapore', 'number' => '65']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 195, 'country_code' => 'SX', 'name' => 'Sint Maarten', 'number' => '1721']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 196, 'country_code' => 'SK', 'name' => 'Slovakia (Slovensko)', 'number' => '421']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 197, 'country_code' => 'SI', 'name' => 'Slovenia (Slovenija)', 'number' => '386']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 198, 'country_code' => 'SB', 'name' => 'Solomon Islands', 'number' => '677']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 199, 'country_code' => 'SO', 'name' => 'Somalia (Soomaaliya)', 'number' => '252']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 200, 'country_code' => 'ZA', 'name' => 'South Africa', 'number' => '27']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 201, 'country_code' => 'GS', 'name' => 'South Georgia & South Sandwich Islands', 'number' => '500']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 202, 'country_code' => 'KR', 'name' => 'South Korea (대한민국)', 'number' => '82']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 203, 'country_code' => 'SS', 'name' => 'South Sudan (‫جنوب السودان‬‎)', 'number' => '211']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 204, 'country_code' => 'ES', 'name' => 'Spain (España)', 'number' => '34']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 205, 'country_code' => 'LK', 'name' => 'Sri Lanka (ශ්‍රී ලංකාව)', 'number' => '94']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 206, 'country_code' => 'SD', 'name' => 'Sudan (‫السودان‬‎)', 'number' => '249']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 207, 'country_code' => 'SR', 'name' => 'Suriname', 'number' => '597']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 208, 'country_code' => 'SJ', 'name' => 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)', 'number' => '4779']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 209, 'country_code' => 'SZ', 'name' => 'Swaziland', 'number' => '268']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 210, 'country_code' => 'SE', 'name' => 'Sweden (Sverige)', 'number' => '46']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 211, 'country_code' => 'CH', 'name' => 'Switzerland (Schweiz)', 'number' => '41']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 212, 'country_code' => 'SY', 'name' => 'Syria (‫سوريا‬‎)', 'number' => '963']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 213, 'country_code' => 'ST', 'name' => 'São Tomé and Príncipe (São Tomé e Príncipe)', 'number' => '239']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 214, 'country_code' => 'TW', 'name' => 'Taiwan (台灣)', 'number' => '886']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 215, 'country_code' => 'TJ', 'name' => 'Tajikistan', 'number' => '992']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 216, 'country_code' => 'TZ', 'name' => 'Tanzania', 'number' => '255']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 217, 'country_code' => 'TH', 'name' => 'Thailand (ไทย)', 'number' => '66']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 218, 'country_code' => 'TL', 'name' => 'Timor-Leste', 'number' => '670']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 219, 'country_code' => 'TG', 'name' => 'Togo', 'number' => '228']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 220, 'country_code' => 'TK', 'name' => 'Tokelau', 'number' => '690']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 221, 'country_code' => 'TO', 'name' => 'Tonga', 'number' => '676']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 222, 'country_code' => 'TT', 'name' => 'Trinidad and Tobago', 'number' => '1868']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 223, 'country_code' => 'TN', 'name' => 'Tunisia (‫تونس‬‎)', 'number' => '216']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 224, 'country_code' => 'TR', 'name' => 'Turkey (Türkiye)', 'number' => '90']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 225, 'country_code' => 'TM', 'name' => 'Turkmenistan', 'number' => '993']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 226, 'country_code' => 'TC', 'name' => 'Turks and Caicos Islands', 'number' => '1649']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 227, 'country_code' => 'TV', 'name' => 'Tuvalu', 'number' => '688']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 228, 'country_code' => 'VI', 'name' => 'U.S. Virgin Islands', 'number' => '1340']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 229, 'country_code' => 'UG', 'name' => 'Uganda', 'number' => '256']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 230, 'country_code' => 'UA', 'name' => 'Ukraine (Україна)', 'number' => '380']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 231, 'country_code' => 'AE', 'name' => 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)', 'number' => '971']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 232, 'country_code' => 'GB', 'name' => 'United Kingdom', 'number' => '44']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 233, 'country_code' => 'US', 'name' => 'United States', 'number' => '1']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 234, 'country_code' => 'UY', 'name' => 'Uruguay', 'number' => '598']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 235, 'country_code' => 'UZ', 'name' => 'Uzbekistan (Oʻzbekiston)', 'number' => '998']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 236, 'country_code' => 'VU', 'name' => 'Vanuatu', 'number' => '678']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 237, 'country_code' => 'VA', 'name' => 'Vatican City (Città del Vaticano)', 'number' => '379']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 238, 'country_code' => 'VE', 'name' => 'Venezuela', 'number' => '58']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 239, 'country_code' => 'VN', 'name' => 'Vietnam (Việt Nam)', 'number' => '84']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 240, 'country_code' => 'WF', 'name' => 'Wallis and Futuna', 'number' => '681']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 241, 'country_code' => 'EH', 'name' => 'Western Sahara (‫الصحراء الغربية‬‎)', 'number' => '212']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 242, 'country_code' => 'YE', 'name' => 'Yemen (‫اليمن‬‎)', 'number' => '967']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 243, 'country_code' => 'ZM', 'name' => 'Zambia', 'number' => '260']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 244, 'country_code' => 'ZW', 'name' => 'Zimbabwe', 'number' => '263']);
        $this->insert(CountryPhoneCode::tableName(), ['id' => 245, 'country_code' => 'AX', 'name' => 'Åland Islands (Åland)', 'number' => '358']);

        /* TODO: pridėti foreign key */
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->truncateTable(CountryPhoneCode::tableName());
    }
}
