<?php

use common\models\Country;
use yii\db\Migration;

/**
 * Class m160719_073720_country_data
 */
class m160719_073720_country_data extends Migration
{
    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->insert(Country::tableName(), ['code' => 'A1', 'name' => 'Anonymous Proxy', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'A2', 'name' => 'Satellite Provider', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AD', 'name' => 'Andorra', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'AE', 'name' => 'United Arab Emirates', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AF', 'name' => 'Afghanistan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AI', 'name' => 'Anguilla', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AL', 'name' => 'Albania', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'AM', 'name' => 'Armenia', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'AN', 'name' => 'Netherlands Antilles', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AO', 'name' => 'Angola', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AP', 'name' => 'Asia/Pacific Region', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AQ', 'name' => 'Antarctica', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AR', 'name' => 'Argentina', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AS', 'name' => 'American Samoa', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AT', 'name' => 'Austria', 'vat_rate' => '20.00']);
        $this->insert(Country::tableName(), ['code' => 'AU', 'name' => 'Australia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AW', 'name' => 'Aruba', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AX', 'name' => 'Aland Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'AZ', 'name' => 'Azerbaijan', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'BB', 'name' => 'Barbados', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BD', 'name' => 'Bangladesh', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BE', 'name' => 'Belgium', 'vat_rate' => '21.00']);
        $this->insert(Country::tableName(), ['code' => 'BF', 'name' => 'Burkina Faso', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BG', 'name' => 'Bulgaria', 'vat_rate' => '20.00']);
        $this->insert(Country::tableName(), ['code' => 'BH', 'name' => 'Bahrain', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BI', 'name' => 'Burundi', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BJ', 'name' => 'Benin', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BM', 'name' => 'Bermuda', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BN', 'name' => 'Brunei Darussalam', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BO', 'name' => 'Bolivia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BR', 'name' => 'Brazil', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BS', 'name' => 'Bahamas', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BT', 'name' => 'Bhutan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BV', 'name' => 'Bouvet Island', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BW', 'name' => 'Botswana', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'BY', 'name' => 'Belarus', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'BZ', 'name' => 'Belize', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CA', 'name' => 'Canada', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CD', 'name' => 'Congo, The Democratic Republic of the', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CF', 'name' => 'Central African Republic', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CG', 'name' => 'Congo', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CH', 'name' => 'Switzerland', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'CI', 'name' => "Cote D'Ivoire", 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CK', 'name' => 'Cook Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CL', 'name' => 'Chile', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CM', 'name' => 'Cameroon', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CN', 'name' => 'China', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CO', 'name' => 'Colombia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CR', 'name' => 'Costa Rica', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CU', 'name' => 'Cuba', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CV', 'name' => 'Cape Verde', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'CY', 'name' => 'Cyprus', 'vat_rate' => '19.00']);
        $this->insert(Country::tableName(), ['code' => 'CZ', 'name' => 'Czech Republic', 'vat_rate' => '21.00']);
        $this->insert(Country::tableName(), ['code' => 'DE', 'name' => 'Germany', 'vat_rate' => '19.00']);
        $this->insert(Country::tableName(), ['code' => 'DJ', 'name' => 'Djibouti', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'DK', 'name' => 'Denmark', 'vat_rate' => '25.00']);
        $this->insert(Country::tableName(), ['code' => 'DM', 'name' => 'Dominica', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'DO', 'name' => 'Dominican Republic', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'DZ', 'name' => 'Algeria', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'EC', 'name' => 'Ecuador', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'EE', 'name' => 'Estonia', 'vat_rate' => '20.00']);
        $this->insert(Country::tableName(), ['code' => 'EG', 'name' => 'Egypt', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'ER', 'name' => 'Eritrea', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'ES', 'name' => 'Spain', 'vat_rate' => '21.00']);
        $this->insert(Country::tableName(), ['code' => 'ET', 'name' => 'Ethiopia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'EU', 'name' => 'Europe', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'FI', 'name' => 'Finland', 'vat_rate' => '24.00']);
        $this->insert(Country::tableName(), ['code' => 'FJ', 'name' => 'Fiji', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'FK', 'name' => 'Falkland Islands [Malvinas]', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'FM', 'name' => 'Micronesia, Federated States of', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'FO', 'name' => 'Faroe Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'FR', 'name' => 'France', 'vat_rate' => '20.00']);
        $this->insert(Country::tableName(), ['code' => 'GA', 'name' => 'Gabon', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GB', 'name' => 'United Kingdom', 'vat_rate' => '20.00']);
        $this->insert(Country::tableName(), ['code' => 'GD', 'name' => 'Grenada', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GE', 'name' => 'Georgia', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'GF', 'name' => 'French Guiana', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GG', 'name' => 'Guernsey', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GH', 'name' => 'Ghana', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GI', 'name' => 'Gibraltar', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GL', 'name' => 'Greenland', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GM', 'name' => 'Gambia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GN', 'name' => 'Guinea', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GP', 'name' => 'Guadeloupe', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GR', 'name' => 'Greece', 'vat_rate' => '23.00']);
        $this->insert(Country::tableName(), ['code' => 'GT', 'name' => 'Guatemala', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GU', 'name' => 'Guam', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GW', 'name' => 'Guinea-Bissau', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'GY', 'name' => 'Guyana', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'HK', 'name' => 'Hong Kong', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'HM', 'name' => 'Heard Island and McDonald Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'HN', 'name' => 'Honduras', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'HR', 'name' => 'Croatia', 'vat_rate' => '25.00']);
        $this->insert(Country::tableName(), ['code' => 'HT', 'name' => 'Haiti', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'HU', 'name' => 'Hungary', 'vat_rate' => '27.00']);
        $this->insert(Country::tableName(), ['code' => 'ID', 'name' => 'Indonesia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IE', 'name' => 'Ireland', 'vat_rate' => '23.00']);
        $this->insert(Country::tableName(), ['code' => 'IL', 'name' => 'Israel', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IM', 'name' => 'Isle of Man', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IN', 'name' => 'India', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IQ', 'name' => 'Iraq', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IR', 'name' => 'Iran, Islamic Republic of', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'IS', 'name' => 'Iceland', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'IT', 'name' => 'Italy', 'vat_rate' => '22.00']);
        $this->insert(Country::tableName(), ['code' => 'JE', 'name' => 'Jersey', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'JM', 'name' => 'Jamaica', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'JO', 'name' => 'Jordan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'JP', 'name' => 'Japan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KE', 'name' => 'Kenya', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KG', 'name' => 'Kyrgyzstan', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'KH', 'name' => 'Cambodia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KI', 'name' => 'Kiribati', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KM', 'name' => 'Comoros', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KP', 'name' => "Korea, Democratic People's Republic of", 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KR', 'name' => 'Korea, Republic of', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KW', 'name' => 'Kuwait', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KY', 'name' => 'Cayman Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'KZ', 'name' => 'Kazakstan', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'LA', 'name' => "Lao People's Democratic Republic", 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LB', 'name' => 'Lebanon', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LC', 'name' => 'Saint Lucia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LI', 'name' => 'Liechtenstein', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LK', 'name' => 'Sri Lanka', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LR', 'name' => 'Liberia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LS', 'name' => 'Lesotho', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'LT', 'name' => 'Lithuania', 'vat_rate' => '21.00']);
        $this->insert(Country::tableName(), ['code' => 'LU', 'name' => 'Luxembourg', 'vat_rate' => '17.00']);
        $this->insert(Country::tableName(), ['code' => 'LV', 'name' => 'Latvia', 'vat_rate' => '21.00']);
        $this->insert(Country::tableName(), ['code' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MA', 'name' => 'Morocco', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MC', 'name' => 'Monaco', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'MD', 'name' => 'Moldova, Republic of', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'ME', 'name' => 'Montenegro', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'MG', 'name' => 'Madagascar', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MH', 'name' => 'Marshall Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MK', 'name' => 'Macedonia', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'ML', 'name' => 'Mali', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MM', 'name' => 'Myanmar', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MN', 'name' => 'Mongolia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MO', 'name' => 'Macau', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MQ', 'name' => 'Martinique', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MR', 'name' => 'Mauritania', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MS', 'name' => 'Montserrat', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MT', 'name' => 'Malta', 'vat_rate' => '18.00']);
        $this->insert(Country::tableName(), ['code' => 'MU', 'name' => 'Mauritius', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MV', 'name' => 'Maldives', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MW', 'name' => 'Malawi', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MX', 'name' => 'Mexico', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MY', 'name' => 'Malaysia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'MZ', 'name' => 'Mozambique', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NA', 'name' => 'Namibia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NC', 'name' => 'New Caledonia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NE', 'name' => 'Niger', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NF', 'name' => 'Norfolk Island', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NG', 'name' => 'Nigeria', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NI', 'name' => 'Nicaragua', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NL', 'name' => 'Netherlands', 'vat_rate' => '21.00']);
        $this->insert(Country::tableName(), ['code' => 'NO', 'name' => 'Norway', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'NP', 'name' => 'Nepal', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NR', 'name' => 'Nauru', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NU', 'name' => 'Niue', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'NZ', 'name' => 'New Zealand', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'OM', 'name' => 'Oman', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PA', 'name' => 'Panama', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PE', 'name' => 'Peru', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PF', 'name' => 'French Polynesia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PG', 'name' => 'Papua New Guinea', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PH', 'name' => 'Philippines', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PK', 'name' => 'Pakistan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PL', 'name' => 'Poland', 'vat_rate' => '23.00']);
        $this->insert(Country::tableName(), ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PR', 'name' => 'Puerto Rico', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PS', 'name' => 'Palestinian Territory, Occupied', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PT', 'name' => 'Portugal', 'vat_rate' => '23.00']);
        $this->insert(Country::tableName(), ['code' => 'PW', 'name' => 'Palau', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'PY', 'name' => 'Paraguay', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'QA', 'name' => 'Qatar', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'RE', 'name' => 'Reunion', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'RO', 'name' => 'Romania', 'vat_rate' => '24.00']);
        $this->insert(Country::tableName(), ['code' => 'RS', 'name' => 'Serbia', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'RU', 'name' => 'Russian Federation', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'RW', 'name' => 'Rwanda', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SA', 'name' => 'Saudi Arabia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SB', 'name' => 'Solomon Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SC', 'name' => 'Seychelles', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SD', 'name' => 'Sudan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SE', 'name' => 'Sweden', 'vat_rate' => '25.00']);
        $this->insert(Country::tableName(), ['code' => 'SG', 'name' => 'Singapore', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SI', 'name' => 'Slovenia', 'vat_rate' => '22.00']);
        $this->insert(Country::tableName(), ['code' => 'SK', 'name' => 'Slovakia', 'vat_rate' => '20.00']);
        $this->insert(Country::tableName(), ['code' => 'SL', 'name' => 'Sierra Leone', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SM', 'name' => 'San Marino', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'SN', 'name' => 'Senegal', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SO', 'name' => 'Somalia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SR', 'name' => 'Suriname', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SV', 'name' => 'El Salvador', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SY', 'name' => 'Syrian Arab Republic', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'SZ', 'name' => 'Swaziland', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TD', 'name' => 'Chad', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TG', 'name' => 'Togo', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TH', 'name' => 'Thailand', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TJ', 'name' => 'Tajikistan', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'TK', 'name' => 'Tokelau', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TM', 'name' => 'Turkmenistan', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'TN', 'name' => 'Tunisia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TO', 'name' => 'Tonga', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TR', 'name' => 'Turkey', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TV', 'name' => 'Tuvalu', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TW', 'name' => 'Taiwan', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'UA', 'name' => 'Ukraine', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'UG', 'name' => 'Uganda', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'US', 'name' => 'United States', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'UY', 'name' => 'Uruguay', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'UZ', 'name' => 'Uzbekistan', 'vat_rate' => '0.00']);
        $this->insert(Country::tableName(), ['code' => 'VA', 'name' => 'Holy See [Vatican City State]', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'VE', 'name' => 'Venezuela', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'VG', 'name' => 'Virgin Islands, British', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'VI', 'name' => 'Virgin Islands, U.S.', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'VN', 'name' => 'Vietnam', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'VU', 'name' => 'Vanuatu', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'WF', 'name' => 'Wallis and Futuna', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'WS', 'name' => 'Samoa', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'YE', 'name' => 'Yemen', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'YT', 'name' => 'Mayotte', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'ZA', 'name' => 'South Africa', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'ZM', 'name' => 'Zambia', 'vat_rate' => null]);
        $this->insert(Country::tableName(), ['code' => 'ZW', 'name' => 'Zimbabwe', 'vat_rate' => null]);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->truncateTable(Country::tableName());
    }
}
