<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-frontend',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'frontend\controllers',
    'language' => 'lt',
    'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => [
                'name' => '_frontendUser0805',
                'domain' => '.al-frontend.local',
                'httpOnly' => true
            ]
        ],
        'cache' => [
            'class' => 'yii\\caching\\FileCache',
            'cachePath' => '@runtime/cache',
            'keyPrefix' => 'al'
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'info'],
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'categories' => ['application'],
                    'logFile' => '@app/runtime/logs/application.log',
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'categories' => ['debug'],
                    'logVars' => [],
                    'logFile' => '@app/runtime/logs/debug.log',
                ],
            ],
        ],
		'geoip' => [
            'class' => 'dpodium\yii2\geoip\components\CGeoIP',
            'mode' => 'STANDARD',  // Choose MEMORY_CACHE or STANDARD mode
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'i18n' => [
            'translations' => [
                'alert*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'app*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'country*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'document*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'duk*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'element*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'mail*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'seo*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'text*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'yii*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
                'log*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@frontend/messages',
                    'sourceLanguage' => 'en',
                    'forceTranslation' => true,
                ],
            ],
        ],
        'urlManager' => [
            'class' => 'common\components\MyUrlManager',
            // Disable index.php
            'showScriptName' => false,
            // Disable r = routes
            'enablePrettyUrl' => true,
            'rules' => [
            // Lithuanian
    
                //region Lithuanian routes
                // SiteController
                '//<lang:(lt)>.<domain>/automobiliu-gabenimas-pervezimas' => 'site/index',
                '//<lang:(lt)>.<domain>/rekvizitai' => 'site/imprint',
                '//<lang:(lt)>.<domain>/apie-mus' => 'site/about-us',
                '//<lang:(lt)>.<domain>/taisykles' => 'site/guidelines',
                '//<lang:(lt)>.<domain>/kaip-naudotis-sistema' => 'site/how-to-use',
                '//<lang:(lt)>.<domain>/pagalba' => 'site/help',
                '//<lang:(lt)>.<domain>/duk-klausimas/<question:[\w\_\-]+>' => 'site/faq-feedback',
                '//<lang:(lt)>.<domain>/duk-klausimas' => 'site/faq-feedback',
                '//<lang:(lt)>.<domain>/informacija-apie-imone' => 'site/company-info-by-vat-code',
                '//<lang:(lt)>.<domain>/keisti-kalba/<language:[a-z]+>' => 'site/change-language',
                '//<lang:(lt)>.<domain>/nustatyti-laiko-zona' => 'site/set-timezone',
                '//<lang:(lt)>.<domain>/prisijungimas' => 'site/login',
                '//<lang:(lt)>.<domain>/registracija' => 'site/sign-up',
                '//<lang:(lt)>.<domain>/registracijos-patikrinimas' => 'site/sign-up-validation',
                '//<lang:(lt)>.<domain>/registracija-sekminga/<email:[\w+\d+\@\.\%]+>/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-successful',
                '//<lang:(lt)>.<domain>/registracija-sekminga/<email:[\w+\d+\@\.\%]+>' => 'site/sign-up-successful',
                '//<lang:(lt)>.<domain>/registracija-sekminga' => 'site/sign-up-successful',
                '//<lang:(lt)>.<domain>/registracijos-patvirtinimas/<token:[0-9a-zA-Z\-\_]+>' => 'site/confirm-sign-up',
                '//<lang:(lt)>.<domain>/registracijos-patvirtinimas' => 'site/confirm-sign-up',
                '//<lang:(lt)>.<domain>/pakvietimas-uzsiregistruoti/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-invitation',
                '//<lang:(lt)>.<domain>/pakvietimas-uzsiregistruoti' => 'site/sign-up-invitation',
                '//<lang:(lt)>.<domain>/pakvietimo-uzsiregistruoti-patikrinimas' => 'site/sign-up-invitation-validation',
                '//<lang:(lt)>.<domain>/slaptazodzio-priminimas' => 'site/request-password-reset',
                '//<lang:(lt)>.<domain>/slaptazodzio-priminimas-nusiustas/<email:[\w+\d+\@\.\%]+>' => 'site/password-reset-sent',
                '//<lang:(lt)>.<domain>/slaptazodzio-priminimas-nusiustas' => 'site/password-reset-sent',
                '//<lang:(lt)>.<domain>/slaptazodzio-atstatymas/<token:[0-9a-zA-Z\-\_]+>' => 'site/reset-password',
                '//<lang:(lt)>.<domain>/slaptazodzio-atstatymas' => 'site/reset-password',
                '//<lang:(lt)>.<domain>/slaptazodis-atstatytas-sekmingai' => 'site/reset-password-successful',
                '//<lang:(lt)>.<domain>/atsijungti' => 'site/logout',
                '//<lang:(lt)>.<domain>/isjungti-prenumeratos-pranesimo-rodyma' => 'site/disable-subscription-alert',
                '//<lang:(lt)>.<domain>/administratoriaus-prisijungimas/<token:[0-9a-zA-Z\-\_]+>' => 'site/login-for-admin',
                '//<lang:(lt)>.<domain>/administratoriaus-prisijungimas' => 'site/login-for-admin',

                // SettingsController
                '//<lang:(lt)>.<domain>/nustatymai/<tab:[\w\-]+>/<subTab:[\w\-]+>' => 'settings/index',
                '//<lang:(lt)>.<domain>/nustatymai/<tab:[\w\-]+>' => 'settings/index',
                '//<lang:(lt)>.<domain>/nustatymai' => 'settings/index',
                '//<lang:(lt)>.<domain>/mano-duomenu-patikrinimas' => 'settings/edit-my-data-validation',
                '//<lang:(lt)>.<domain>/mano-duomenys' => 'settings/edit-my-data',
                '//<lang:(lt)>.<domain>/pasto-keitimas' => 'settings/request-email-change',
                '//<lang:(lt)>.<domain>/keisti-imones-duomenis' => 'settings/contact-info',
                '//<lang:(lt)>.<domain>/imones-duomenu-patikrinimas' => 'settings/contact-info-validation',
                '//<lang:(lt)>.<domain>/keisti-pvm-koda' => 'settings/request-vat-code-change',
                '//<lang:(lt)>.<domain>/prideti-dokumenta/<type:[A-Z]+>/<date:[0-9\-]+>' => 'settings/add-document',
                '//<lang:(lt)>.<domain>/prideti-dokumenta/<type:[A-Z]+>' => 'settings/add-document',
                '//<lang:(lt)>.<domain>/prideti-dokumenta' => 'settings/add-document',
//                '//<lang:(lt)>.<domain>/pasalinti-dokumenta/<type:[A-Z]+>' => 'settings/remove-document',
//                '//<lang:(lt)>.<domain>/pasalinti-dokumenta' => 'settings/remove-document',
                '//<lang:(lt)>.<domain>/keisti-slaptazodi' => 'settings/change-password',
                '//<lang:(lt)>.<domain>/parsisiusti-dokumenta/<type:[A-Z]+>' => 'settings/download-document',
                '//<lang:(lt)>.<domain>/parsisiusti-dokumenta' => 'settings/download-document',
                '//<lang:(lt)>.<domain>/pakvietimo-issiuntimas' => 'settings/invitation',
                '//<lang:(lt)>.<domain>/pakvietimas-issiustas/<email:[\w+\d+\@\.\%]+>' => 'settings/invitation-successful',
                '//<lang:(lt)>.<domain>/pakvietimas-issiustas' => 'settings/invitation-successful',
                '//<lang:(lt)>.<domain>/pakvietimo-issiuntimo-patikrinimas' => 'settings/invitation-validation',
                '//<lang:(lt)>.<domain>/issiusti-pakvietima' => 'settings/send-invitation',

                // SubscriptionController
                '//<lang:(lt)>.<domain>/prenumerata/<tab:[\w\-]+>/<isPaid:[\d]>' => 'subscription/index',
                '//<lang:(lt)>.<domain>/prenumerata/<tab:[\w\-]+>' => 'subscription/index',
                '//<lang:(lt)>.<domain>/prenumerata' => 'subscription/index',
                '//<lang:(lt)>.<domain>/parsisiusti-saskaita-faktura/<id:\d+>/<type:\d>' => 'subscription/download-invoice',
                '//<lang:(lt)>.<domain>/parsisiusti-saskaita-faktura/<id:\d+>' => 'subscription/download-invoice',
                '//<lang:(lt)>.<domain>/parsisiusti-saskaita-faktura/' => 'subscription/download-invoice',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimas-sekmingas/' => 'subscription/service-payment-accept',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimas-nesekmingas/' => 'subscription/service-payment-cancel',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimo-metodas/<id:\d+>/<method:\d>' => 'subscription/service-payment-method',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimo-metodas/<id:\d+>' => 'subscription/service-payment-method',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimo-metodas/' => 'subscription/service-payment-method',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimo-atsakymas/<method:\d>' => 'subscription/service-payment-callback',
                '//<lang:(lt)>.<domain>/paslaugos-apmokejimo-atsakymas/' => 'subscription/service-payment-callback',
                '//<lang:(lt)>.<domain>/prekes-pasirinkimas' => 'subscription/service-selection',
                '//<lang:(lt)>.<domain>/prekes-patvirtinimas' => 'subscription/service-confirmation',
                '//<lang:(lt)>.<domain>/prekes-pirkimas' => 'subscription/service-purchase',
                '//<lang:(lt)>.<domain>/prekes-aktyvavimas' => 'subscription/service-activation',
                '//<lang:(lt)>.<domain>/grizti-i-prekes-pirkima' => 'subscription/back-to-service-purchase',
                '//<lang:(lt)>.<domain>/paslaugos-pratesimo-priminimas/<token:[A-Za-z0-9]+>' => 'subscription/reminder',
                '//<lang:(lt)>.<domain>/paslaugos-pratesimo-priminimas' => 'subscription/reminder',
                '//<lang:(lt)>.<domain>/pasalinti-pasibaigusias-aktyvias-paslaugas/<token:[A-Za-z0-9]+>' => 'subscription/remove-ended-active-services',
                '//<lang:(lt)>.<domain>/pasalinti-pasibaigusias-aktyvias-paslaugas' => 'subscription/remove-ended-active-services',
                '//<lang:(lt)>.<domain>/atnaujinti-dabartinius-kreditus/<token:[A-Za-z0-9]+>' => 'subscription/update-current-credits',
                '//<lang:(lt)>.<domain>/atnaujinti-dabartinius-kreditus' => 'subscription/update-current-credits',

                // LoadController
                '//<lang:(lt)>.<domain>/mano-skelbimai/<page:\d+>/<per-page:\d+>' => 'my-announcement/index',
                '//<lang:(lt)>.<domain>/mano-skelbimai/<token:[0-9a-zA-Z\-\_]+>' => 'my-announcement/index',
                '//<lang:(lt)>.<domain>/mano-skelbimai' => 'my-announcement/index',
                '//<lang:(lt)>.<domain>/skelbti-krovini' => 'load/announce',
                '//<lang:(lt)>.<domain>/skelbiamo-krovinio-patikrinimas' => 'load/announce-validation',
                '//<lang:(lt)>.<domain>/ieskoti-krovinio' => 'load/search',
                '//<lang:(lt)>.<domain>/kroviniai-jusu-autoveziui' => 'load/search-results',
                '//<lang:(lt)>.<domain>/krovinio-informacijos-perziura' => 'load/preview',
                '//<lang:(lt)>.<domain>/roundtrips' => 'load/round-trips',
                '//<lang:(lt)>.<domain>/roundtrips/<cityId:\d+>' => 'load/round-trips-results',
                '//<lang:(lt)>.<domain>/kroviniu-isjungimas/<token:[0-9a-zA-Z]+>' => 'load/deactivate',
                '//<lang:(lt)>.<domain>/kroviniu-isjungimas' => 'load/deactivate',
                '//<lang:(lt)>.<domain>/senu-kroviniu-pasalinimas/<token:[0-9a-zA-Z]+>' => 'load/remove-old',
                '//<lang:(lt)>.<domain>/senu-kroviniu-pasalinimas' => 'load/remove-old',
                '//<lang:(lt)>.<domain>/paslepti-kroviniu-pasiulyma' => 'load/hide-load-suggestion',
                '//<lang:(lt)>.<domain>/kroviniu-pasiulymai' => 'load/suggestions',
                '//<lang:(lt)>.<domain>/kroviniu-pasiulymų-filtro-patikrinimas' => 'load/validate-suggestions-filter',
                '//<lang:(lt)>.<domain>/kroviniai' => 'load/loads',
                '//<lang:(lt)>.<domain>/perziureti-krovinio-informacija' => 'load/preview-load-info',
                '//<lang:(lt)>.<domain>/kroviniu-pasiulymu-siuntimas/<token:[0-9a-zA-Z]+>' => 'load/check-for-newest-suggestions',
                '//<lang:(lt)>.<domain>/kroviniu-pasiulymu-siuntimas' => 'load/check-for-newest-suggestions',

                // CronJobController
                '//<lang:(lt)>.<domain>/neapmoketu-saskaitu-priminimas/<token:[A-Za-z0-9]+>' => 'cron-job/unpaid-bills-reminder',
                '//<lang:(lt)>.<domain>/neapmoketu-saskaitu-priminimas' => 'cron-job/unpaid-bills-reminder',
                '//<lang:(lt)>.<domain>/atnaujinti-vartotoju-kreditus/<token:[A-Za-z0-9]+>' => 'cron-job/update-users-credits',
                '//<lang:(lt)>.<domain>/atnaujinti-vartotoju-kreditus' => 'cron-job/update-users-credits',
                '//<lang:(lt)>.<domain>/imoniu-archyvavimas/<token:[A-Za-z0-9]+>' => 'cron-job/companies-archivation',
                '//<lang:(lt)>.<domain>/imoniu-archyvavimas' => 'cron-job/companies-archivation',
                '//<lang:(lt)>.<domain>/vartotoju-archyvavimas/<token:[A-Za-z0-9]+>' => 'cron-job/users-archivation',
                '//<lang:(lt)>.<domain>/vartotoju-archyvavimas' => 'cron-job/users-archivation',
                '//<lang:(lt)>.<domain>/kroviniu-sumu-perskaiciavimas/<token:[A-Za-z0-9]+>' => 'cron-job/recalculate-loads-totals',

                // RedirectsController
                '//<lang:(lt)>.<domain>/paslaugos-ir-saskaitos' => 'redirects/services-and-invoices',
                '//<lang:(lt)>.<domain>/naudojimo-taisykles' => 'redirects/guidelines',
                '//<lang:(lt)>.<domain>/pamirsote-slaptazodi' => 'redirects/request-password-reset',
                '//<lang:(lt)>.<domain>/isigyti-prenumerata' => 'redirects/buy-subscription',
                '//<lang:(lt)>.<domain>/aktyvios-paslaugos' => 'redirects/active-services',
                '//<lang:(lt)>.<domain>/apmoketos-saskaitos' => 'redirects/paid-invoices',
                '//<lang:(lt)>.<domain>/keisti-mano-duomenis' => 'redirects/change-my-data',
                '//<lang:(lt)>.<domain>/keisti-imones-duomenis' => 'redirects/change-company-data',

                // CarTransporterAnnouncementController
                '//<lang:(lt)>.<domain>/skelbti-autovezi' => 'car-transporter-announcement/announcement-form',

                // CarTransporterController
                '//<lang:(lt)>.<domain>/autovežiai' => 'car-transporter/index',
                '//<lang:(lt)>.<domain>/autoveziu-isjungimas/<token:[0-9a-zA-Z]+>' => 'car-transporter/deactivate',
                '//<lang:(lt)>.<domain>/autoveziu-isjungimas' => 'car-transporter/deactivate',
                '//<lang:(lt)>.<domain>/senu-autoveziu-pasalinimas/<token:[0-9a-zA-Z]+>' => 'car-transporter/remove-old',
                '//<lang:(lt)>.<domain>/senu-autoveziu-pasalinimas' => 'car-transporter/remove-old',

                // CarTransporterSearchController
                '//<lang:(lt)>.<domain>/ieskoti-autovezio' => 'car-transporter-search/search-form',
                '//<lang:(lt)>.<domain>/autovezio-paieskos-rezultatai' => 'car-transporter-search/search',
                //endregion

                '//<lang:(lt)>.<domain>/my-loads' => 'my-announcement/index',

                // English
    
                //region English routes
                // SiteController
                '//<lang:(en)>.<domain>/car-transport' => 'site/index',
                '//<lang:(en)>.<domain>/imprint' => 'site/imprint',
                '//<lang:(en)>.<domain>/about-us' => 'site/about-us',
                '//<lang:(en)>.<domain>/guidelines' => 'site/guidelines',
                '//<lang:(en)>.<domain>/how-to-use' => 'site/how-to-use',
                '//<lang:(en)>.<domain>/help' => 'site/help',
                '//<lang:(en)>.<domain>/faq-question/<question:[\w\_\-]+>' => 'site/faq-feedback',
                '//<lang:(en)>.<domain>/faq-question' => 'site/faq-feedback',
                '//<lang:(en)>.<domain>/info-about-company' => 'site/company-info-by-vat-code',
                '//<lang:(en)>.<domain>/change-language/<language:[a-z]+>' => 'site/change-language',
                '//<lang:(en)>.<domain>/timezone-offset' => 'site/set-timezone',
                '//<lang:(en)>.<domain>/login' => 'site/login',
                '//<lang:(en)>.<domain>/sign-up' => 'site/sign-up',
                '//<lang:(en)>.<domain>/sign-up-validation' => 'site/sign-up-validation',
                '//<lang:(en)>.<domain>/sign-up-successful/<email:[\w+\d+\@\.\%]+>/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-successful',
                '//<lang:(en)>.<domain>/sign-up-successful/<email:[\w+\d+\@\.\%]+>' => 'site/sign-up-successful',
                '//<lang:(en)>.<domain>/sign-up-successful' => 'site/sign-up-successful',
                '//<lang:(en)>.<domain>/sign-up-confirmation/<token:[0-9a-zA-Z\-\_]+>' => 'site/confirm-sign-up',
                '//<lang:(en)>.<domain>/sign-up-confirmation' => 'site/confirm-sign-up',
                '//<lang:(en)>.<domain>/invitation-to-sign-up/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-invitation',
                '//<lang:(en)>.<domain>/invitation-to-sign-up' => 'site/sign-up-invitation',
                '//<lang:(en)>.<domain>/invitation-to-sign-up-validation' => 'site/sign-up-invitation-validation',
                '//<lang:(en)>.<domain>/forgot-the-password' => 'site/request-password-reset',
                '//<lang:(en)>.<domain>/password-reset-sent/<email:[\w+\d+\@\.\%]+>' => 'site/password-reset-sent',
                '//<lang:(en)>.<domain>/password-reset-sent' => 'site/password-reset-sent',
                '//<lang:(en)>.<domain>/password-reset/<token:[0-9a-zA-Z\-\_]+>' => 'site/reset-password',
                '//<lang:(en)>.<domain>/password-reset' => 'site/reset-password',
                '//<lang:(en)>.<domain>/password-reset-successful' => 'site/reset-password-successful',
                '//<lang:(en)>.<domain>/logout' => 'site/logout',
                '//<lang:(en)>.<domain>/disable-subscription-alert' => 'site/disable-subscription-alert',

                // SettingsController
                '//<lang:(en)>.<domain>/settings/<tab:[\w\-]+>/<subTab:[\w\-]+>' => 'settings/index',
                '//<lang:(en)>.<domain>/settings/<tab:[\w\-]+>' => 'settings/index',
                '//<lang:(en)>.<domain>/settings' => 'settings/index',
                '//<lang:(en)>.<domain>/my-data-validation' => 'settings/edit-my-data-validation',
                '//<lang:(en)>.<domain>/my-data' => 'settings/edit-my-data',
                '//<lang:(en)>.<domain>/change-email' => 'settings/request-email-change',
                '//<lang:(en)>.<domain>/change-company-data' => 'settings/contact-info',
                '//<lang:(en)>.<domain>/company-data-validation' => 'settings/contact-info-validation',
                '//<lang:(en)>.<domain>/change-vat-code' => 'settings/request-vat-code-change',
                '//<lang:(en)>.<domain>/add-document/<type:[A-Z]+>/<date:[0-9\-]+>' => 'settings/add-document',
                '//<lang:(en)>.<domain>/add-document/<type:[A-Z]+>' => 'settings/add-document',
                '//<lang:(en)>.<domain>/add-document' => 'settings/add-document',
//                '//<lang:(en)>.<domain>/remove-document/<type:[A-Z]+>' => 'settings/remove-document',
//                '//<lang:(en)>.<domain>/remove-document' => 'settings/remove-document',
                '//<lang:(en)>.<domain>/change-password' => 'settings/change-password',
                '//<lang:(en)>.<domain>/download-document/<type:[A-Z]+>' => 'settings/download-document',
                '//<lang:(en)>.<domain>/download-document' => 'settings/download-document',
                '//<lang:(en)>.<domain>/invitation' => 'settings/invitation',
                '//<lang:(en)>.<domain>/invitation-sent/<email:[\w+\d+\@\.\%]+>' => 'settings/invitation-successful',
                '//<lang:(en)>.<domain>/invitation-sent' => 'settings/invitation-successful',
                '//<lang:(en)>.<domain>/invitation-validation' => 'settings/invitation-validation',
                '//<lang:(en)>.<domain>/send-invitation' => 'settings/send-invitation',

                // SubscriptionController
                '//<lang:(en)>.<domain>/subscription/<tab:[\w\-]+>/<isPaid:[\d]>' => 'subscription/index',
                '//<lang:(en)>.<domain>/subscription/<tab:[\w\-]+>' => 'subscription/index',
                '//<lang:(en)>.<domain>/subscription' => 'subscription/index',
                '//<lang:(en)>.<domain>/download-invoice/<id:\d+>/<type:\d>' => 'subscription/download-invoice',
                '//<lang:(en)>.<domain>/download-invoice/<id:\d+>' => 'subscription/download-invoice',
                '//<lang:(en)>.<domain>/download-invoice/' => 'subscription/download-invoice',
                '//<lang:(en)>.<domain>/service-payment-successful/' => 'subscription/service-payment-accept',
                '//<lang:(en)>.<domain>/service-payment-unsuccessful/' => 'subscription/service-payment-cancel',
                '//<lang:(en)>.<domain>/service-payment-method/<id:\d+>/<method:\d>' => 'subscription/service-payment-method',
                '//<lang:(en)>.<domain>/service-payment-method/<id:\d+>' => 'subscription/service-payment-method',
                '//<lang:(en)>.<domain>/service-payment-method/' => 'subscription/service-payment-method',
                '//<lang:(en)>.<domain>/service-payment-callback/<method:\d>' => 'subscription/service-payment-callback',
                '//<lang:(en)>.<domain>/service-payment-callback/' => 'subscription/service-payment-callback',
                '//<lang:(en)>.<domain>/service-selection' => 'subscription/service-selection',
                '//<lang:(en)>.<domain>/service-confirmation' => 'subscription/service-confirmation',
                '//<lang:(en)>.<domain>/service-purchase' => 'subscription/service-purchase',
                '//<lang:(en)>.<domain>/service-activation' => 'subscription/service-activation',
                '//<lang:(en)>.<domain>/back-to-service-purchase' => 'subscription/back-to-service-purchase',
                '//<lang:(en)>.<domain>/subscription-extension-reminder/<token:[A-Za-z0-9]+>' => 'subscription/reminder',
                '//<lang:(en)>.<domain>/subscription-extension-reminder' => 'subscription/reminder',
                '//<lang:(en)>.<domain>/remove-ended-active-services/<token:[A-Za-z0-9]+>' => 'subscription/remove-ended-active-services',
                '//<lang:(en)>.<domain>/remove-ended-active-services' => 'subscription/remove-ended-active-services',
                '//<lang:(en)>.<domain>/update-current-credits/<token:[A-Za-z0-9]+>' => 'subscription/update-current-credits',
                '//<lang:(en)>.<domain>/update-current-credits' => 'subscription/update-current-credits',

                // LoadController
                '//<lang:(en)>.<domain>/my-loads/<page:\d+>/<per-page:\d+>' => 'my-announcement/index',
                '//<lang:(en)>.<domain>/my-loads/<token:[0-9a-zA-Z\-\_]+>' => 'my-announcement/index',
                '//<lang:(en)>.<domain>/my-loads' => 'my-announcement/index',
                '//<lang:(en)>.<domain>/announce-load' => 'load/announce',
                '//<lang:(en)>.<domain>/announce-load-validation' => 'load/announce-validation',
                '//<lang:(en)>.<domain>/search-for-load' => 'load/search',
                '//<lang:(en)>.<domain>/loads-for-your-transporter' => 'load/search-results',
                '//<lang:(en)>.<domain>/load-information-preview' => 'load/preview',
                '//<lang:(en)>.<domain>/roundtrips' => 'load/round-trips',
                '//<lang:(en)>.<domain>/roundtrips/<cityId:\d+>' => 'load/round-trips-results',
                '//<lang:(en)>.<domain>/loads-deactivation/<token:[0-9a-zA-Z]+>' => 'load/deactivate',
                '//<lang:(en)>.<domain>/loads-deactivation' => 'load/deactivate',
                '//<lang:(en)>.<domain>/remove-old-loads/<token:[0-9a-zA-Z]+>' => 'load/remove-old',
                '//<lang:(en)>.<domain>/remove-old-loads' => 'load/remove-old',
                '//<lang:(en)>.<domain>/hide-load-suggestion' => 'load/hide-load-suggestion',
                '//<lang:(en)>.<domain>/load-suggestions' => 'load/suggestions',
                '//<lang:(en)>.<domain>/load-suggestions-filter-validation' => 'load/validate-suggestions-filter',
                '//<lang:(en)>.<domain>/loads' => 'load/loads',
                '//<lang:(en)>.<domain>/preview-load-info' => 'load/preview-load-info',

                // RedirectsController
                '//<lang:(en)>.<domain>/account/subscriptions-and-invoices' => 'redirects/services-and-invoices',
                '//<lang:(en)>.<domain>/account/profile-settings' => 'redirects/settings',
                '//<lang:(en)>.<domain>/search-to-load' => 'redirects/search-load',
                '//<lang:(en)>.<domain>/add-shipment' => 'redirects/announce-load',
                '//<lang:(en)>.<domain>/my-shippments' => 'redirects/my-loads',
                '//<lang:(en)>.<domain>/delivery-offers' => 'redirects/load-suggestions',
                '//<lang:(en)>.<domain>/forgot-the-password' => 'redirects/request-password-reset',
                '//<lang:(en)>.<domain>/buy-membership' => 'redirects/buy-subscription',
                '//<lang:(en)>.<domain>/activated-services' => 'redirects/active-services',
                '//<lang:(en)>.<domain>/my-invoices' => 'redirects/paid-invoices',
                '//<lang:(en)>.<domain>/edit-my-profile' => 'redirects/change-my-data',

                // CarTransporterAnnouncementController
                '//<lang:(en)>.<domain>/announce-car-transporter' => 'car-transporter-announcement/announcement-form',

                // CarTransporterController
                '//<lang:(en)>.<domain>/car-transporters' => 'car-transporter/index',

                // CarTransporterSearchController
                '//<lang:(en)>.<domain>/search-car-transporter' => 'car-transporter-search/search-form',
                '//<lang:(en)>.<domain>/car-transporter-search-results' => 'car-transporter-search/search',
                //endregion

            // Polish
    
                //region Polish routes
                // SiteController
                '//<lang:(pl)>.<domain>/transport-samachodow' => 'site/index',
                '//<lang:(pl)>.<domain>/dane-teleadresowe' => 'site/imprint',
                './/<lang:(pl)>.<domain>/o-nas' => 'site/about-us',
                '//<lang:(pl)>.<domain>/przepisy' => 'site/guidelines',
                '//<lang:(pl)>.<domain>/jak-korzystac' => 'site/how-to-use',
                '//<lang:(pl)>.<domain>/pomoc' => 'site/help',
                '//<lang:(pl)>.<domain>/faq-question/<question:[\w\_\-]+>' => 'site/faq-feedback',
                '//<lang:(pl)>.<domain>/faq-question' => 'site/faq-feedback',
                '//<lang:(pl)>.<domain>/info-about-company' => 'site/company-info-by-vat-code',
                '//<lang:(pl)>.<domain>/change-language/<language:[a-z]+>' => 'site/change-language',
                '//<lang:(pl)>.<domain>/timezone-offset' => 'site/set-timezone',
                '//<lang:(pl)>.<domain>/logowanie' => 'site/login',
                '//<lang:(pl)>.<domain>/rejestracja' => 'site/sign-up',
                '//<lang:(pl)>.<domain>/rejestracja-validation' => 'site/sign-up-validation',
                '//<lang:(pl)>.<domain>/rejestracja-uzytkownika/<email:[\w+\d+\@\.\%]+>/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-successful',
                '//<lang:(pl)>.<domain>/rejestracja-uzytkownika/<email:[\w+\d+\@\.\%]+>' => 'site/sign-up-successful',
                '//<lang:(pl)>.<domain>/rejestracja-uzytkownika' => 'site/sign-up-successful',
                '//<lang:(pl)>.<domain>/rejestracja-confirmation/<token:[0-9a-zA-Z\-\_]+>' => 'site/confirm-sign-up',
                '//<lang:(pl)>.<domain>/rejestracja-confirmation' => 'site/confirm-sign-up',
                '//<lang:(pl)>.<domain>/zaproszenie-do-rejestracji/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-invitation',
                '//<lang:(pl)>.<domain>/zaproszenie-do-rejestracji' => 'site/sign-up-invitation',
                '//<lang:(pl)>.<domain>/zaproszenie-do-rejestracji-validation' => 'site/sign-up-invitation-validation',
                '//<lang:(pl)>.<domain>/zapomniales-hasla' => 'site/request-password-reset',
                '//<lang:(pl)>.<domain>/wyslano-przypomnienie-hasla/<email:[\w+\d+\@\.\%]+>' => 'site/password-reset-sent',
                '//<lang:(pl)>.<domain>/wyslano-przypomnienie-hasla' => 'site/password-reset-sent',
                '//<lang:(pl)>.<domain>/zmiana-hasla/<token:[0-9a-zA-Z\-\_]+>' => 'site/reset-password',
                '//<lang:(pl)>.<domain>/zmiana-hasla' => 'site/reset-password',
                '//<lang:(pl)>.<domain>/haslo-pomyslnie-odzyskano' => 'site/reset-password-successful',
                '//<lang:(pl)>.<domain>/wyloguj' => 'site/logout',
                '//<lang:(pl)>.<domain>/disable-subscription-alert' => 'site/disable-subscription-alert',

                // SettingsController
                '//<lang:(pl)>.<domain>/ustawienia/<tab:[\w\-]+>/<subTab:[\w\-]+>' => 'settings/index',
                '//<lang:(pl)>.<domain>/ustawienia/<tab:[\w\-]+>' => 'settings/index',
                '//<lang:(pl)>.<domain>/ustawienia' => 'settings/index',
                '//<lang:(pl)>.<domain>/zmien-moje-dane-validation' => 'settings/edit-my-data-validation',
                '//<lang:(pl)>.<domain>/zmien-moje-dane' => 'settings/edit-my-data',
                '//<lang:(pl)>.<domain>/zmien-email' => 'settings/request-email-change',
                '//<lang:(pl)>.<domain>/zmien-dane' => 'settings/contact-info',
                '//<lang:(pl)>.<domain>/dane-validation' => 'settings/contact-info-validation',
                '//<lang:(pl)>.<domain>/zmien-vat-code' => 'settings/request-vat-code-change',
                '//<lang:(pl)>.<domain>/dokumenty/<type:[A-Z]+>/<date:[0-9\-]+>' => 'settings/add-document',
                '//<lang:(pl)>.<domain>/dokumenty/<type:[A-Z]+>' => 'settings/add-document',
                '//<lang:(pl)>.<domain>/dokumenty' => 'settings/add-document',
//                '//<lang:(pl)>.<domain>/remove-document/<type:[A-Z]+>' => 'settings/remove-document',
//                '//<lang:(pl)>.<domain>/remove-document' => 'settings/remove-document',
                '//<lang:(pl)>.<domain>/zmien-hasla' => 'settings/change-password',
                '//<lang:(pl)>.<domain>/download-document/<type:[A-Z]+>' => 'settings/download-document',
                '//<lang:(pl)>.<domain>/download-document' => 'settings/download-document',
                '//<lang:(pl)>.<domain>/zaproszenia' => 'settings/invitation',
                '//<lang:(pl)>.<domain>/zaproszenie-wyslano/<email:[\w+\d+\@\.\%]+>' => 'settings/invitation-successful',
                '//<lang:(pl)>.<domain>/zaproszenie-wyslano' => 'settings/invitation-successful',
                '//<lang:(pl)>.<domain>/zaproszenie-validation' => 'settings/invitation-validation',
                '//<lang:(pl)>.<domain>/wyslij-zaproszenie' => 'settings/send-invitation',

                // SubscriptionController
                '//<lang:(pl)>.<domain>/uslugi-i-rachunki/<tab:[\w\-]+>/<isPaid:[\d]>' => 'subscription/index',
                '//<lang:(pl)>.<domain>/uslugi-i-rachunki/<tab:[\w\-]+>' => 'subscription/index',
                '//<lang:(pl)>.<domain>/uslugi-i-rachunki' => 'subscription/index',
                '//<lang:(pl)>.<domain>/download-invoice/<id:\d+>/<type:\d>' => 'subscription/download-invoice',
                '//<lang:(pl)>.<domain>/download-invoice/<id:\d+>' => 'subscription/download-invoice',
                '//<lang:(pl)>.<domain>/download-invoice/' => 'subscription/download-invoice',
                '//<lang:(pl)>.<domain>/service-payment-successful/' => 'subscription/service-payment-accept',
                '//<lang:(pl)>.<domain>/service-payment-unsuccessful/' => 'subscription/service-payment-cancel',
                '//<lang:(pl)>.<domain>/service-payment-method/<id:\d+>/<method:\d>' => 'subscription/service-payment-method',
                '//<lang:(pl)>.<domain>/service-payment-method/<id:\d+>' => 'subscription/service-payment-method',
                '//<lang:(pl)>.<domain>/service-payment-method/' => 'subscription/service-payment-method',
                '//<lang:(pl)>.<domain>/service-payment-callback/<method:\d>' => 'subscription/service-payment-callback',
                '//<lang:(pl)>.<domain>/service-payment-callback/' => 'subscription/service-payment-callback',
                '//<lang:(pl)>.<domain>/service-selection' => 'subscription/service-selection',
                '//<lang:(pl)>.<domain>/service-confirmation' => 'subscription/service-confirmation',
                '//<lang:(pl)>.<domain>/service-purchase' => 'subscription/service-purchase',
                '//<lang:(pl)>.<domain>/service-activation' => 'subscription/service-activation',
                '//<lang:(pl)>.<domain>/back-to-service-purchase' => 'subscription/back-to-service-purchase',
                '//<lang:(pl)>.<domain>/subscription-extension-reminder/<token:[A-Za-z0-9]+>' => 'subscription/reminder',
                '//<lang:(pl)>.<domain>/subscription-extension-reminder' => 'subscription/reminder',
                '//<lang:(pl)>.<domain>/remove-ended-active-services/<token:[A-Za-z0-9]+>' => 'subscription/remove-ended-active-services',
                '//<lang:(pl)>.<domain>/remove-ended-active-services' => 'subscription/remove-ended-active-services',
                '//<lang:(pl)>.<domain>/update-current-credits/<token:[A-Za-z0-9]+>' => 'subscription/update-current-credits',
                '//<lang:(pl)>.<domain>/update-current-credits' => 'subscription/update-current-credits',

                // LoadController
                '//<lang:(pl)>.<domain>/moje-ogloszenia/<page:\d+>/<per-page:\d+>' => 'my-announcement/index',
                '//<lang:(pl)>.<domain>/moje-ogloszenia/<token:[0-9a-zA-Z\-\_]+>' => 'my-announcement/index',
                '//<lang:(pl)>.<domain>/moje-ogloszenia' => 'my-announcement/index',
                '//<lang:(pl)>.<domain>/oglos-ladunek' => 'load/announce',
                '//<lang:(pl)>.<domain>/oglos-ladunek-validation' => 'load/announce-validation',
                '//<lang:(pl)>.<domain>/szukaj-ladunku' => 'load/search',
                '//<lang:(pl)>.<domain>/ladunki-na-twoja-lawete' => 'load/search-results',
                '//<lang:(pl)>.<domain>/load-information-preview' => 'load/preview',
                '//<lang:(pl)>.<domain>/roundtrips' => 'load/round-trips',
                '//<lang:(pl)>.<domain>/roundtrips/<cityId:\d+>' => 'load/round-trips-results',
                '//<lang:(pl)>.<domain>/loads-deactivation/<token:[0-9a-zA-Z]+>' => 'load/deactivate',
                '//<lang:(pl)>.<domain>/loads-deactivation' => 'load/deactivate',
                '//<lang:(pl)>.<domain>/remove-old-loads/<token:[0-9a-zA-Z]+>' => 'load/remove-old',
                '//<lang:(pl)>.<domain>/remove-old-loads' => 'load/remove-old',
                '//<lang:(pl)>.<domain>/hide-load-suggestion' => 'load/hide-load-suggestion',
                '//<lang:(pl)>.<domain>/oferty-ladunkow' => 'load/suggestions',
                '//<lang:(pl)>.<domain>/oferty-ladunkow-filter-validation' => 'load/validate-suggestions-filter',
                '//<lang:(pl)>.<domain>/ładunki' => 'load/loads',
            
                // RedirectsController
                '//<lang:(pl)>.<domain>/account/uslugi-i-faktury' => 'redirects/services-and-invoices',
                '//<lang:(pl)>.<domain>/login' => 'redirects/login',
                '//<lang:(pl)>.<domain>/account/ustawienia-profilu' => 'redirects/settings',
                '//<lang:(pl)>.<domain>/rekwizyty' => 'redirects/imprint',
                '//<lang:(pl)>.<domain>/regulamin' => 'redirects/guidelines',
                '//<lang:(pl)>.<domain>/jak-uzywac' => 'redirects/how-to-use',
                '//<lang:(pl)>.<domain>/przegladaj-przesylki' => 'redirects/search-load',
                '//<lang:(pl)>.<domain>/zglosic-przewoz' => 'redirects/announce-load',
                '//<lang:(pl)>.<domain>/nie-pamietam-hasla' => 'redirects/request-password-reset',
                '//<lang:(pl)>.<domain>/nabyj-prenumerate' => 'redirects/buy-subscription',
                '//<lang:(pl)>.<domain>/aktywowane-uslugi' => 'redirects/active-services',
                '//<lang:(pl)>.<domain>/moje-faktury' => 'redirects/paid-invoices',
                '//<lang:(pl)>.<domain>/zmien-dane-firmy' => 'redirects/change-company-data',
                '//<lang:(pl)>.<domain>/wyslac-zaproszenie' => 'redirects/invitation',

                // CarTransporterAnnouncementController
                '//<lang:(pl)>.<domain>/announce-car-transporter' => 'car-transporter-announcement/announcement-form',

                // CarTransporterController
                '//<lang:(pl)>.<domain>/wolny-transport' => 'car-transporter/index',

                // CarTransporterSearchController
                '//<lang:(pl)>.<domain>/search-car-transporter' => 'car-transporter-search/search-form',
                '//<lang:(pl)>.<domain>/car-transporter-search-results' => 'car-transporter-search/search',
                //endregion

                '//<lang:(pl)>.<domain>/my-loads' => 'my-announcement/index',

                // Russian
    
                //region Russian routes
                // SiteController
                '//<lang:(ru)>.<domain>/перевозка-автомобилей' => 'site/index',
                '//<lang:(ru)>.<domain>/pеквизиты' => 'site/imprint',
                '//<lang:(ru)>.<domain>/o-нас' => 'site/about-us',
                '//<lang:(ru)>.<domain>/правила' => 'site/guidelines',
                '//<lang:(ru)>.<domain>/как-пользоваться' => 'site/how-to-use',
                '//<lang:(ru)>.<domain>/помощь' => 'site/help',
                '//<lang:(ru)>.<domain>/faq-question/<question:[\w\_\-]+>' => 'site/faq-feedback',
                '//<lang:(ru)>.<domain>/faq-question' => 'site/faq-feedback',
                '//<lang:(ru)>.<domain>/info-about-company' => 'site/company-info-by-vat-code',
                '//<lang:(ru)>.<domain>/change-language/<language:[a-z]+>' => 'site/change-language',
                '//<lang:(ru)>.<domain>/timezone-offset' => 'site/set-timezone',
                '//<lang:(ru)>.<domain>/войти' => 'site/login',
                '//<lang:(ru)>.<domain>/pегистрация' => 'site/sign-up',
                '//<lang:(ru)>.<domain>/pегистрация-validation' => 'site/sign-up-validation',
                '//<lang:(ru)>.<domain>/pегистрация-пользователя/<email:[\w+\d+\@\.\%]+>/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-successful',
                '//<lang:(ru)>.<domain>/pегистрация-пользователя/<email:[\w+\d+\@\.\%]+>' => 'site/sign-up-successful',
                '//<lang:(ru)>.<domain>/pегистрация-пользователя' => 'site/sign-up-successful',
                '//<lang:(ru)>.<domain>/pегистрация-confirmation/<token:[0-9a-zA-Z\-\_]+>' => 'site/confirm-sign-up',
                '//<lang:(ru)>.<domain>/pегистрация-confirmation' => 'site/confirm-sign-up',
                '//<lang:(ru)>.<domain>/приглашение-на-регистрацию/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-invitation',
                '//<lang:(ru)>.<domain>/приглашение-на-регистрацию' => 'site/sign-up-invitation',
                '//<lang:(ru)>.<domain>/приглашение-на-регистрацию-validation' => 'site/sign-up-invitation-validation',
                '//<lang:(ru)>.<domain>/забыли-пароль' => 'site/request-password-reset',
                '//<lang:(ru)>.<domain>/восстановление-пароля-отправлено/<email:[\w+\d+\@\.\%]+>' => 'site/password-reset-sent',
                '//<lang:(ru)>.<domain>/восстановление-пароля-отправлено' => 'site/password-reset-sent',
                '//<lang:(ru)>.<domain>/изменение-пароля/<token:[0-9a-zA-Z\-\_]+>' => 'site/reset-password',
                '//<lang:(ru)>.<domain>/изменение-пароля' => 'site/reset-password',
                '//<lang:(ru)>.<domain>/пароль-успешно-восстановлен' => 'site/reset-password-successful',
                '//<lang:(ru)>.<domain>/выйти' => 'site/logout',
                '//<lang:(ru)>.<domain>/disable-subscription-alert' => 'site/disable-subscription-alert',

                // SettingsController
                '//<lang:(ru)>.<domain>/настройки/<tab:[\w\-]+>/<subTab:[\w\-]+>' => 'settings/index',
                '//<lang:(ru)>.<domain>/настройки/<tab:[\w\-]+>' => 'settings/index',
                '//<lang:(ru)>.<domain>/настройки' => 'settings/index',
                '//<lang:(ru)>.<domain>/изменить-мои-данные-validation' => 'settings/edit-my-data-validation',
                '//<lang:(ru)>.<domain>/изменить-мои-данные' => 'settings/edit-my-data',
                '//<lang:(ru)>.<domain>/изменить-зл-почта' => 'settings/request-email-change',
                '//<lang:(ru)>.<domain>/изменить-данные' => 'settings/contact-info',
                '//<lang:(ru)>.<domain>/данные-validation' => 'settings/contact-info-validation',
                '//<lang:(ru)>.<domain>/изменить-vat-code' => 'settings/request-vat-code-change',
                '//<lang:(ru)>.<domain>/add-document/<type:[A-Z]+>/<date:[0-9\-]+>' => 'settings/add-document',
                '//<lang:(ru)>.<domain>/add-document/<type:[A-Z]+>' => 'settings/add-document',
                '//<lang:(ru)>.<domain>/add-document' => 'settings/add-document',
//                '//<lang:(ru)>.<domain>/remove-document/<type:[A-Z]+>' => 'settings/remove-document',
//                '//<lang:(ru)>.<domain>/remove-document' => 'settings/remove-document',
                '//<lang:(ru)>.<domain>/изменить-пароль' => 'settings/change-password',
                '//<lang:(ru)>.<domain>/download-document/<type:[A-Z]+>' => 'settings/download-document',
                '//<lang:(ru)>.<domain>/download-document' => 'settings/download-document',
                '//<lang:(ru)>.<domain>/приглашение' => 'settings/invitation',
                '//<lang:(ru)>.<domain>/приглашение-отправлено/<email:[\w+\d+\@\.\%]+>' => 'settings/invitation-successful',
                '//<lang:(ru)>.<domain>/приглашение-отправлено' => 'settings/invitation-successful',
                '//<lang:(ru)>.<domain>/приглашение-validation' => 'settings/invitation-validation',
                '//<lang:(ru)>.<domain>/oтправить-приглашение' => 'settings/send-invitation',

                // SubscriptionController
                '//<lang:(ru)>.<domain>/yслуги-и-счета/<tab:[\w\-]+>/<isPaid:[\d]>' => 'subscription/index',
                '//<lang:(ru)>.<domain>/yслуги-и-счета/<tab:[\w\-]+>' => 'subscription/index',
                '//<lang:(ru)>.<domain>/yслуги-и-счета' => 'subscription/index',
                '//<lang:(ru)>.<domain>/download-invoice/<id:\d+>/<type:\d>' => 'subscription/download-invoice',
                '//<lang:(ru)>.<domain>/download-invoice/<id:\d+>' => 'subscription/download-invoice',
                '//<lang:(ru)>.<domain>/download-invoice/' => 'subscription/download-invoice',
                '//<lang:(ru)>.<domain>/service-payment-successful/' => 'subscription/service-payment-accept',
                '//<lang:(ru)>.<domain>/service-payment-unsuccessful/' => 'subscription/service-payment-cancel',
                '//<lang:(ru)>.<domain>/service-payment-method/<id:\d+>/<method:\d>' => 'subscription/service-payment-method',
                '//<lang:(ru)>.<domain>/service-payment-method/<id:\d+>' => 'subscription/service-payment-method',
                '//<lang:(ru)>.<domain>/service-payment-method/' => 'subscription/service-payment-method',
                '//<lang:(ru)>.<domain>/service-payment-callback/<method:\d>' => 'subscription/service-payment-callback',
                '//<lang:(ru)>.<domain>/service-payment-callback/' => 'subscription/service-payment-callback',
                '//<lang:(ru)>.<domain>/service-selection' => 'subscription/service-selection',
                '//<lang:(ru)>.<domain>/service-confirmation' => 'subscription/service-confirmation',
                '//<lang:(ru)>.<domain>/service-purchase' => 'subscription/service-purchase',
                '//<lang:(ru)>.<domain>/service-activation' => 'subscription/service-activation',
                '//<lang:(ru)>.<domain>/back-to-service-purchase' => 'subscription/back-to-service-purchase',
                '//<lang:(ru)>.<domain>/subscription-extension-reminder/<token:[A-Za-z0-9]+>' => 'subscription/reminder',
                '//<lang:(ru)>.<domain>/subscription-extension-reminder' => 'subscription/reminder',
                '//<lang:(ru)>.<domain>/remove-ended-active-services/<token:[A-Za-z0-9]+>' => 'subscription/remove-ended-active-services',
                '//<lang:(ru)>.<domain>/remove-ended-active-services' => 'subscription/remove-ended-active-services',
                '//<lang:(ru)>.<domain>/update-current-credits/<token:[A-Za-z0-9]+>' => 'subscription/update-current-credits',
                '//<lang:(ru)>.<domain>/update-current-credits' => 'subscription/update-current-credits',

                // LoadController
                '//<lang:(ru)>.<domain>/мои-объявления/<page:\d+>/<per-page:\d+>' => 'my-announcement/index',
                '//<lang:(ru)>.<domain>/мои-объявления/<token:[0-9a-zA-Z\-\_]+>' => 'my-announcement/index',
                '//<lang:(ru)>.<domain>/мои-объявления' => 'my-announcement/index',
                '//<lang:(ru)>.<domain>/pазместить-груз' => 'load/announce',
                '//<lang:(ru)>.<domain>/pазместить-груз-validation' => 'load/announce-validation',
                '//<lang:(ru)>.<domain>/поиск-груза' => 'load/search',
                '//<lang:(ru)>.<domain>/грузы-для-вашего-автовоза' => 'load/search-results',
                '//<lang:(ru)>.<domain>/load-information-preview' => 'load/preview',
                '//<lang:(ru)>.<domain>/pоундтpипс' => 'load/round-trips',
                '//<lang:(ru)>.<domain>/pоундтpипс/<cityId:\d+>' => 'load/round-trips-results',
                '//<lang:(ru)>.<domain>/loads-deactivation/<token:[0-9a-zA-Z]+>' => 'load/deactivate',
                '//<lang:(ru)>.<domain>/loads-deactivation' => 'load/deactivate',
                '//<lang:(ru)>.<domain>/remove-old-loads/<token:[0-9a-zA-Z]+>' => 'load/remove-old',
                '//<lang:(ru)>.<domain>/remove-old-loads' => 'load/remove-old',
                '//<lang:(ru)>.<domain>/hide-load-suggestion' => 'load/hide-load-suggestion',
                '//<lang:(ru)>.<domain>/предложения-грузов' => 'load/suggestions',
                '//<lang:(ru)>.<domain>/предложения-грузов-filter-validation' => 'load/validate-suggestions-filter',
            
                // RedirectsController
                '//<lang:(ru)>.<domain>/yслуги-и-фактуры' => 'redirects/services-and-invoices',
                '//<lang:(ru)>.<domain>/логин' => 'redirects/login',
                '//<lang:(ru)>.<domain>/данные-компании' => 'redirects/imprint',
                '//<lang:(ru)>.<domain>/рaзмеcтить-зaпроc' => 'redirects/announce-load',
                '//<lang:(ru)>.<domain>/предложение-грузитcя' => 'redirects/load-suggestions',
                '//<lang:(ru)>.<domain>/пoкупaть-пoдпиcку' => 'redirects/buy-subscription',
                '//<lang:(ru)>.<domain>/мoи-уcлуги' => 'redirects/active-services',
                '//<lang:(ru)>.<domain>/мoи-пoкупки' => 'redirects/paid-invoices',
                '//<lang:(ru)>.<domain>/изменить-данные-фирму' => 'redirects/change-company-data',

                // CarTransporterAnnouncementController
                '//<lang:(ru)>.<domain>/announce-car-transporter' => 'car-transporter-announcement/announcement-form',

                // CarTransporterController
                '//<lang:(ru)>.<domain>/автовозы' => 'car-transporter/index',

                // CarTransporterSearchController
                '//<lang:(ru)>.<domain>/search-car-transporter' => 'car-transporter-search/search-form',
                '//<lang:(ru)>.<domain>/car-transporter-search-results' => 'car-transporter-search/search',
                //endregion
                '//<lang:(ru)>.<domain>/my-loads' => 'my-announcement/index',

            // Deutsch
    
                //region German routes
                // SiteController
                '//<lang:(de)>.<domain>/fahrzeugtransport' => 'site/index',
                '//<lang:(de)>.<domain>/impressum' => 'site/imprint',
                '//<lang:(de)>.<domain>/uber-uns' => 'site/about-us',
                '//<lang:(de)>.<domain>/regeln' => 'site/guidelines',
                '//<lang:(de)>.<domain>/wie-benutzt-man' => 'site/how-to-use',
                '//<lang:(de)>.<domain>/hilfe' => 'site/help',
                '//<lang:(de)>.<domain>/faq-question/<question:[\w\_\-]+>' => 'site/faq-feedback',
                '//<lang:(de)>.<domain>/faq-question' => 'site/faq-feedback',
                '//<lang:(de)>.<domain>/info-about-company' => 'site/company-info-by-vat-code',
                '//<lang:(de)>.<domain>/change-language/<language:[a-z]+>' => 'site/change-language',
                '//<lang:(de)>.<domain>/timezone-offset' => 'site/set-timezone',
                '//<lang:(de)>.<domain>/einloggen' => 'site/login',
                '//<lang:(de)>.<domain>/anmeldung' => 'site/sign-up',
                '//<lang:(de)>.<domain>/anmeldung-validation' => 'site/sign-up-validation',
                '//<lang:(de)>.<domain>/anmeldung-des-benutzers/<email:[\w+\d+\@\.\%]+>/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-successful',
                '//<lang:(de)>.<domain>/anmeldung-des-benutzers/<email:[\w+\d+\@\.\%]+>' => 'site/sign-up-successful',
                '//<lang:(de)>.<domain>/anmeldung-des-benutzers' => 'site/sign-up-successful',
                '//<lang:(de)>.<domain>/anmeldung-confirmation/<token:[0-9a-zA-Z\-\_]+>' => 'site/confirm-sign-up',
                '//<lang:(de)>.<domain>/anmeldung-confirmation' => 'site/confirm-sign-up',
                '//<lang:(de)>.<domain>/anmelden-einladung/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-invitation',
                '//<lang:(de)>.<domain>/anmelden-einladung' => 'site/sign-up-invitation',
                '//<lang:(de)>.<domain>/anmelden-einladung-validation' => 'site/sign-up-invitation-validation',
                '//<lang:(de)>.<domain>/haben-sie-das-passwort-vergessen' => 'site/request-password-reset',
                '//<lang:(de)>.<domain>/es-wurde-die-passwort-erinnerung-gesendet/<email:[\w+\d+\@\.\%]+>' => 'site/password-reset-sent',
                '//<lang:(de)>.<domain>/es-wurde-die-passwort-erinnerung-gesendet' => 'site/password-reset-sent',
                '//<lang:(de)>.<domain>/passwortänderung/<token:[0-9a-zA-Z\-\_]+>' => 'site/reset-password',
                '//<lang:(de)>.<domain>/passwortänderung' => 'site/reset-password',
                '//<lang:(de)>.<domain>/passwort-wurde-erfolgreich-wiederhergestellt' => 'site/reset-password-successful',
                '//<lang:(de)>.<domain>/ausloggen' => 'site/logout',
                '//<lang:(de)>.<domain>/disable-subscription-alert' => 'site/disable-subscription-alert',

                // SettingsController
                '//<lang:(de)>.<domain>/einstellungen/<tab:[\w\-]+>/<subTab:[\w\-]+>' => 'settings/index',
                '//<lang:(de)>.<domain>/einstellungen/<tab:[\w\-]+>' => 'settings/index',
                '//<lang:(de)>.<domain>/einstellungen' => 'settings/index',
                '//<lang:(de)>.<domain>/meine-daten-andern-validation' => 'settings/edit-my-data-validation',
                '//<lang:(de)>.<domain>/meine-daten-andern' => 'settings/edit-my-data',
                '//<lang:(de)>.<domain>/e-mail-andern' => 'settings/request-email-change',
                '//<lang:(de)>.<domain>/daten-andern' => 'settings/contact-info',
                '//<lang:(de)>.<domain>/daten-andern-validation' => 'settings/contact-info-validation',
                '//<lang:(de)>.<domain>/vat-code-ändern' => 'settings/request-vat-code-change',
                '//<lang:(de)>.<domain>/add-document/<type:[A-Z]+>/<date:[0-9\-]+>' => 'settings/add-document',
                '//<lang:(de)>.<domain>/add-document/<type:[A-Z]+>' => 'settings/add-document',
                '//<lang:(de)>.<domain>/add-document' => 'settings/add-document',
//                '//<lang:(de)>.<domain>/remove-document/<type:[A-Z]+>' => 'settings/remove-document',
//                '//<lang:(de)>.<domain>/remove-document' => 'settings/remove-document',
                '//<lang:(de)>.<domain>/password-andern' => 'settings/change-password',
                '//<lang:(de)>.<domain>/download-document/<type:[A-Z]+>' => 'settings/download-document',
                '//<lang:(de)>.<domain>/download-document' => 'settings/download-document',
                '//<lang:(de)>.<domain>/einladung' => 'settings/invitation',
                '//<lang:(de)>.<domain>/einladung-gesendet/<email:[\w+\d+\@\.\%]+>' => 'settings/invitation-successful',
                '//<lang:(de)>.<domain>/einladung-gesendet' => 'settings/invitation-successful',
                '//<lang:(de)>.<domain>/einladung-validation' => 'settings/invitation-validation',
                '//<lang:(de)>.<domain>/senden-der-einladung' => 'settings/send-invitation',

                // SubscriptionController
                '//<lang:(de)>.<domain>/services-und-rechnungen/<tab:[\w\-]+>/<isPaid:[\d]>' => 'subscription/index',
                '//<lang:(de)>.<domain>/services-und-rechnungen/<tab:[\w\-]+>' => 'subscription/index',
                '//<lang:(de)>.<domain>/services-und-rechnungen' => 'subscription/index',
                '//<lang:(de)>.<domain>/download-invoice/<id:\d+>/<type:\d>' => 'subscription/download-invoice',
                '//<lang:(de)>.<domain>/download-invoice/<id:\d+>' => 'subscription/download-invoice',
                '//<lang:(de)>.<domain>/download-invoice/' => 'subscription/download-invoice',
                '//<lang:(de)>.<domain>/service-payment-successful/' => 'subscription/service-payment-accept',
                '//<lang:(de)>.<domain>/service-payment-unsuccessful/' => 'subscription/service-payment-cancel',
                '//<lang:(de)>.<domain>/service-payment-method/<id:\d+>/<method:\d>' => 'subscription/service-payment-method',
                '//<lang:(de)>.<domain>/service-payment-method/<id:\d+>' => 'subscription/service-payment-method',
                '//<lang:(de)>.<domain>/service-payment-method/' => 'subscription/service-payment-method',
                '//<lang:(de)>.<domain>/service-payment-callback/<method:\d>' => 'subscription/service-payment-callback',
                '//<lang:(de)>.<domain>/service-payment-callback/' => 'subscription/service-payment-callback',
                '//<lang:(de)>.<domain>/service-selection' => 'subscription/service-selection',
                '//<lang:(de)>.<domain>/service-confirmation' => 'subscription/service-confirmation',
                '//<lang:(de)>.<domain>/service-purchase' => 'subscription/service-purchase',
                '//<lang:(de)>.<domain>/service-activation' => 'subscription/service-activation',
                '//<lang:(de)>.<domain>/back-to-service-purchase' => 'subscription/back-to-service-purchase',
                '//<lang:(de)>.<domain>/subscription-extension-reminder/<token:[A-Za-z0-9]+>' => 'subscription/reminder',
                '//<lang:(de)>.<domain>/subscription-extension-reminder' => 'subscription/reminder',
                '//<lang:(de)>.<domain>/remove-ended-active-services/<token:[A-Za-z0-9]+>' => 'subscription/remove-ended-active-services',
                '//<lang:(de)>.<domain>/remove-ended-active-services' => 'subscription/remove-ended-active-services',
                '//<lang:(de)>.<domain>/update-current-credits/<token:[A-Za-z0-9]+>' => 'subscription/update-current-credits',
                '//<lang:(de)>.<domain>/update-current-credits' => 'subscription/update-current-credits',

                // LoadController
                '//<lang:(de)>.<domain>/meine-anzeigen/<page:\d+>/<per-page:\d+>' => 'my-announcement/index',
                '//<lang:(de)>.<domain>/meine-anzeigen/<token:[0-9a-zA-Z\-\_]+>' => 'my-announcement/index',
                '//<lang:(de)>.<domain>/meine-anzeigen' => 'my-announcement/index',
                '//<lang:(de)>.<domain>/fracht-bekanntgeben' => 'load/announce',
                '//<lang:(de)>.<domain>/fracht-bekanntgeben-validation' => 'load/announce-validation',
                '//<lang:(de)>.<domain>/frachtsuche' => 'load/search',
                '//<lang:(de)>.<domain>/frachten-für-ihren-transporter' => 'load/search-results',
                '//<lang:(de)>.<domain>/load-information-preview' => 'load/preview',
                '//<lang:(de)>.<domain>/roundtrips' => 'load/round-trips',
                '//<lang:(de)>.<domain>/roundtrips/<cityId:\d+>' => 'load/round-trips-results',
                '//<lang:(de)>.<domain>/loads-deactivation/<token:[0-9a-zA-Z]+>' => 'load/deactivate',
                '//<lang:(de)>.<domain>/loads-deactivation' => 'load/deactivate',
                '//<lang:(de)>.<domain>/remove-old-loads/<token:[0-9a-zA-Z]+>' => 'load/remove-old',
                '//<lang:(de)>.<domain>/remove-old-loads' => 'load/remove-old',
                '//<lang:(de)>.<domain>/hide-load-suggestion' => 'load/hide-load-suggestion',
                '//<lang:(de)>.<domain>/frachtangebote' => 'load/suggestions',
                '//<lang:(de)>.<domain>/frachtangebote-filter-validation' => 'load/validate-suggestions-filter',
            
                // RedirectsController
                '//<lang:(de)>.<domain>/dienstleistungen-und-rechnungen' => 'redirects/services-and-invoices',
                '//<lang:(de)>.<domain>/login' => 'redirects/login',
                '//<lang:(de)>.<domain>/registrieren' => 'redirects/sign-up',
                '//<lang:(de)>.<domain>/wie-benutzen' => 'redirects/how-to-use',
                '//<lang:(de)>.<domain>/transportauftrage-suchen' => 'redirects/search-load',
                '//<lang:(de)>.<domain>/angebote-erhalten' => 'redirects/announce-load',
                '//<lang:(de)>.<domain>/maine-auftrage' => 'redirects/my-loads',
                '//<lang:(de)>.<domain>/transportauftrage' => 'redirects/load-suggestions',
                '//<lang:(de)>.<domain>/passwort-vergessen' => 'redirects/request-password-reset',
                '//<lang:(de)>.<domain>/abonnement-zu-kaufen' => 'redirects/buy-subscription',
                '//<lang:(de)>.<domain>/aktive-dienstleistungen' => 'redirects/active-services',
                '//<lang:(de)>.<domain>/maine-rechnungen' => 'redirects/paid-invoices',
                '//<lang:(de)>.<domain>/mein-profil-bearbeiten' => 'redirects/change-my-data',
                '//<lang:(de)>.<domain>/unternehme-profil-bearbeiten' => 'redirects/change-company-data',
                '//<lang:(de)>.<domain>/einladung-senden' => 'redirects/invitation',

                // CarTransporterAnnouncementController
                '//<lang:(de)>.<domain>/announce-car-transporter' => 'car-transporter-announcement/announcement-form',

                // CarTransporterController
                '//<lang:(de)>.<domain>/autotransporter' => 'car-transporter/index',

                // CarTransporterSearchController
                '//<lang:(de)>.<domain>/search-car-transporter' => 'car-transporter-search/search-form',
                '//<lang:(de)>.<domain>/car-transporter-search-results' => 'car-transporter-search/search',
                //endregion
                '//<lang:(de)>.<domain>/my-loads' => 'my-announcement/index',

            // Spanish
    
                //region Spanish routes
                // SiteController
                '//<lang:(es)>.<domain>/transportacion-de-vehiculos' => 'site/index',
                '//<lang:(es)>.<domain>/requisitos' => 'site/imprint',
                '//<lang:(es)>.<domain>/acerca-de-nosotros' => 'site/about-us',
                '//<lang:(es)>.<domain>/normas' => 'site/guidelines',
                '//<lang:(es)>.<domain>/como-usar' => 'site/how-to-use',
                '//<lang:(es)>.<domain>/ayuda' => 'site/help',
                '//<lang:(es)>.<domain>/faq-question/<question:[\w\_\-]+>' => 'site/faq-feedback',
                '//<lang:(es)>.<domain>/faq-question' => 'site/faq-feedback',
                '//<lang:(es)>.<domain>/info-about-company' => 'site/company-info-by-vat-code',
                '//<lang:(es)>.<domain>/change-language/<language:[a-z]+>' => 'site/change-language',
                '//<lang:(es)>.<domain>/timezone-offset' => 'site/set-timezone',
                '//<lang:(es)>.<domain>/iniciar-sesión' => 'site/login',
                '//<lang:(es)>.<domain>/registrarse' => 'site/sign-up',
                '//<lang:(es)>.<domain>/registrarse-validation' => 'site/sign-up-validation',
                '//<lang:(es)>.<domain>/registro-de-usuario/<email:[\w+\d+\@\.\%]+>/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-successful',
                '//<lang:(es)>.<domain>/registro-de-usuario/<email:[\w+\d+\@\.\%]+>' => 'site/sign-up-successful',
                '//<lang:(es)>.<domain>/registro-de-usuario' => 'site/sign-up-successful',
                '//<lang:(es)>.<domain>/registrarse-confirmation/<token:[0-9a-zA-Z\-\_]+>' => 'site/confirm-sign-up',
                '//<lang:(es)>.<domain>/registrarse-confirmation' => 'site/confirm-sign-up',
                '//<lang:(es)>.<domain>/invitacion-de-registrarse/<token:[0-9a-zA-Z\-\_]+>' => 'site/sign-up-invitation',
                '//<lang:(es)>.<domain>/invitacion-de-registrarse' => 'site/sign-up-invitation',
                '//<lang:(es)>.<domain>/invitacion-de-registrarse-validation' => 'site/sign-up-invitation-validation',
                '//<lang:(es)>.<domain>/ha-olvidado-su-contrasena' => 'site/request-password-reset',
                '//<lang:(es)>.<domain>/le-ha-sido-enviado-el-recordatorio-de-contrasena/<email:[\w+\d+\@\.\%]+>' => 'site/password-reset-sent',
                '//<lang:(es)>.<domain>/le-ha-sido-enviado-el-recordatorio-de-contrasena' => 'site/password-reset-sent',
                '//<lang:(es)>.<domain>/cambio-de-contrasena/<token:[0-9a-zA-Z\-\_]+>' => 'site/reset-password',
                '//<lang:(es)>.<domain>/cambio-de-contrasena' => 'site/reset-password',
                '//<lang:(es)>.<domain>/contrasena-reestablecida-con-exito' => 'site/reset-password-successful',
                '//<lang:(es)>.<domain>/cerrar-sesion' => 'site/logout',
                '//<lang:(es)>.<domain>/disable-subscription-alert' => 'site/disable-subscription-alert',

                // SettingsController
                '//<lang:(es)>.<domain>/configuracion/<tab:[\w\-]+>/<subTab:[\w\-]+>' => 'settings/index',
                '//<lang:(es)>.<domain>/configuracion/<tab:[\w\-]+>' => 'settings/index',
                '//<lang:(es)>.<domain>/configuracion' => 'settings/index',
                '//<lang:(es)>.<domain>/modificar-mis-datos-validation' => 'settings/edit-my-data-validation',
                '//<lang:(es)>.<domain>/modificar-mis-datos' => 'settings/edit-my-data',
                '//<lang:(es)>.<domain>/modificar-correo-electronico' => 'settings/request-email-change',
                '//<lang:(es)>.<domain>/modificar-datos' => 'settings/contact-info',
                '//<lang:(es)>.<domain>/modificar-datos-validation' => 'settings/contact-info-validation',
                '//<lang:(es)>.<domain>/modificar-vat-code' => 'settings/request-vat-code-change',
                '//<lang:(es)>.<domain>/add-document/<type:[A-Z]+>/<date:[0-9\-]+>' => 'settings/add-document',
                '//<lang:(es)>.<domain>/add-document/<type:[A-Z]+>' => 'settings/add-document',
                '//<lang:(es)>.<domain>/add-document' => 'settings/add-document',
//                '//<lang:(es)>.<domain>/remove-document/<type:[A-Z]+>' => 'settings/remove-document',
//                '//<lang:(es)>.<domain>/remove-document' => 'settings/remove-document',
                '//<lang:(es)>.<domain>/modificar-password' => 'settings/change-password',
                '//<lang:(es)>.<domain>/download-document/<type:[A-Z]+>' => 'settings/download-document',
                '//<lang:(es)>.<domain>/download-document' => 'settings/download-document',
                '//<lang:(es)>.<domain>/invitacion' => 'settings/invitation',
                '//<lang:(es)>.<domain>/invitacion-enviada/<email:[\w+\d+\@\.\%]+>' => 'settings/invitation-successful',
                '//<lang:(es)>.<domain>/Invitacion-enviada' => 'settings/invitation-successful',
                '//<lang:(es)>.<domain>/Invitacion-validation' => 'settings/invitation-validation',
                '//<lang:(es)>.<domain>/envio-de-la-invitacion' => 'settings/send-invitation',

                // SubscriptionController
                '//<lang:(es)>.<domain>/servicios-y-facturas/<tab:[\w\-]+>/<isPaid:[\d]>' => 'subscription/index',
                '//<lang:(es)>.<domain>/servicios-y-facturas/<tab:[\w\-]+>' => 'subscription/index',
                '//<lang:(es)>.<domain>/servicios-y-facturas' => 'subscription/index',
                '//<lang:(es)>.<domain>/download-invoice/<id:\d+>/<type:\d>' => 'subscription/download-invoice',
                '//<lang:(es)>.<domain>/download-invoice/<id:\d+>' => 'subscription/download-invoice',
                '//<lang:(es)>.<domain>/download-invoice/' => 'subscription/download-invoice',
                '//<lang:(es)>.<domain>/service-payment-successful/' => 'subscription/service-payment-accept',
                '//<lang:(es)>.<domain>/service-payment-unsuccessful/' => 'subscription/service-payment-cancel',
                '//<lang:(es)>.<domain>/service-payment-method/<id:\d+>/<method:\d>' => 'subscription/service-payment-method',
                '//<lang:(es)>.<domain>/service-payment-method/<id:\d+>' => 'subscription/service-payment-method',
                '//<lang:(es)>.<domain>/service-payment-method/' => 'subscription/service-payment-method',
                '//<lang:(es)>.<domain>/service-payment-callback/<method:\d>' => 'subscription/service-payment-callback',
                '//<lang:(es)>.<domain>/service-payment-callback/' => 'subscription/service-payment-callback',
                '//<lang:(es)>.<domain>/service-selection' => 'subscription/service-selection',
                '//<lang:(es)>.<domain>/service-confirmation' => 'subscription/service-confirmation',
                '//<lang:(es)>.<domain>/service-purchase' => 'subscription/service-purchase',
                '//<lang:(es)>.<domain>/service-activation' => 'subscription/service-activation',
                '//<lang:(es)>.<domain>/back-to-service-purchase' => 'subscription/back-to-service-purchase',
                '//<lang:(es)>.<domain>/subscription-extension-reminder/<token:[A-Za-z0-9]+>' => 'subscription/reminder',
                '//<lang:(es)>.<domain>/subscription-extension-reminder' => 'subscription/reminder',
                '//<lang:(es)>.<domain>/remove-ended-active-services/<token:[A-Za-z0-9]+>' => 'subscription/remove-ended-active-services',
                '//<lang:(es)>.<domain>/remove-ended-active-services' => 'subscription/remove-ended-active-services',
                '//<lang:(es)>.<domain>/update-current-credits/<token:[A-Za-z0-9]+>' => 'subscription/update-current-credits',
                '//<lang:(es)>.<domain>/update-current-credits' => 'subscription/update-current-credits',

                // LoadController
                '//<lang:(es)>.<domain>/mis-anuncios/<page:\d+>/<per-page:\d+>' => 'my-announcement/index',
                '//<lang:(es)>.<domain>/mis-anuncios/<token:[0-9a-zA-Z\-\_]+>' => 'my-announcement/index',
                '//<lang:(es)>.<domain>/mis-anuncios' => 'my-announcement/index',
                '//<lang:(es)>.<domain>/anunciar-carga' => 'load/announce',
                '//<lang:(es)>.<domain>/anunciar-carga-validation' => 'load/announce-validation',
                '//<lang:(es)>.<domain>/buscar-carga' => 'load/search',
                '//<lang:(es)>.<domain>/cargas-para-su-camión-portavehículos' => 'load/search-results',
                '//<lang:(es)>.<domain>/load-information-preview' => 'load/preview',
                '//<lang:(es)>.<domain>/roundtrips' => 'load/round-trips',
                '//<lang:(es)>.<domain>/roundtrips/<cityId:\d+>' => 'load/round-trips-results',
                '//<lang:(es)>.<domain>/loads-deactivation/<token:[0-9a-zA-Z]+>' => 'load/deactivate',
                '//<lang:(es)>.<domain>/loads-deactivation' => 'load/deactivate',
                '//<lang:(es)>.<domain>/remove-old-loads/<token:[0-9a-zA-Z]+>' => 'load/remove-old',
                '//<lang:(es)>.<domain>/remove-old-loads' => 'load/remove-old',
                '//<lang:(es)>.<domain>/hide-load-suggestion' => 'load/hide-load-suggestion',
                '//<lang:(es)>.<domain>/ofertas-de-cargas' => 'load/suggestions',
                '//<lang:(es)>.<domain>/ofertas-de-cargas-filter-validation' => 'load/validate-suggestions-filter',
                
                // RedirectsController
                '//<lang:(es)>.<domain>/transporte-de-coches' => 'redirects/index',
                '//<lang:(es)>.<domain>/iniciar' => 'redirects/login',
                '//<lang:(es)>.<domain>/registrar' => 'redirects/sign-up',
                '//<lang:(es)>.<domain>/ajustes' => 'redirects/settings',
                '//<lang:(es)>.<domain>/compania' => 'redirects/imprint',
                '//<lang:(es)>.<domain>/sobre-nosotros' => 'redirects/about-us',
                '//<lang:(es)>.<domain>/reglas-de-uso' => 'redirects/guidelines',
                '//<lang:(es)>.<domain>/como-utilizar' => 'redirects/how-to-use',
                '//<lang:(es)>.<domain>/encontrar-envios' => 'redirects/search-load',
                '//<lang:(es)>.<domain>/publicar-envio' => 'redirects/announce-load',
                '//<lang:(es)>.<domain>/mis-envios' => 'redirects/my-loads',
                '//<lang:(es)>.<domain>/ofertas-envio' => 'redirects/load-suggestions',
                '//<lang:(es)>.<domain>/olvidado-contrasena' => 'redirects/request-password-reset',
                '//<lang:(es)>.<domain>/comprar-la-membresia' => 'redirects/buy-subscription',
                '//<lang:(es)>.<domain>/servicios-activos' => 'redirects/active-services',
                '//<lang:(es)>.<domain>/facturas-pagadas' => 'redirects/paid-invoices',
                '//<lang:(es)>.<domain>/editar-mi-perfil' => 'redirects/change-my-data',
                '//<lang:(es)>.<domain>/editar-profil-corporativo' => 'redirects/change-company-data',
                '//<lang:(es)>.<domain>/enviar-invitacion' => 'redirects/invitation',

                // CarTransporterAnnouncementController
                '//<lang:(es)>.<domain>/announce-car-transporter' => 'car-transporter-announcement/announcement-form',

                // CarTransporterController
                '//<lang:(es)>.<domain>/portavehiculos' => 'car-transporter/index',

                // CarTransporterSearchController
                '//<lang:(es)>.<domain>/search-car-transporter' => 'car-transporter-search/search-form',
                '//<lang:(es)>.<domain>/car-transporter-search-results' => 'car-transporter-search/search',
                //endregion
                '//<lang:(es)>.<domain>/my-loads' => 'my-announcement/index',

            // Common

                '//<lang>.<domain>/<controller:\w+>/<action:[\w\-]+>' => '<controller>/<action>',
                '//<lang>.<domain>/<controller:\w+>/<id:\d+>' => '<controller>/view',
                '//<lang>.<domain>/<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '//<lang>.<domain>/<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ],
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'localhost',
                'port' => '1025',
            ],
        ],
        'elasticsearch' => [
            'class' => 'yii\elasticsearch\Connection',
            'nodes' => [
                ['http_address' => 'localhost:9200'],
            ],
        ],
        'session' => [
            'name' => 'PHPFRONTSESSID0805',
            'savePath' => sys_get_temp_dir(),
            'cookieParams' => [
                'domain' => '.al-frontend.local',
                'httpOnly' => true,
            ],
        ],
        'request' => [
            'enableCookieValidation' => true,
            'enableCsrfValidation' => true,
            'cookieValidationKey' => '2T6RN9FzNDrdElc4JTXPrPD6OTuroSGC',
            'csrfParam' => '_frontendCSRF',
            'csrfCookie' => [
                'httpOnly' => true,
                'domain' => '.al-frontend.local',
            ],
        ],
    ],
    'as beforeRequest' => [
        'class' => 'common\components\Languages',
    ],
    'params' => $params,
];
